// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1f8016c2711a0971 "Trillo (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className,
	className2,
	css,
	css2,
	fonts,
	fonts2,
	routes,
} from "./chunks/chunk-EISIRDZY.js";

// virtual:grow-section
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ZqeR0xJIQSkteerOkJ6f/uMqreds5uf3jmT8eMTMM/TeA9qhnZ8.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition,
	Image,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/lQ041B3EytBdPOjwXEwT/BvXiWe3QqnskV3h1FtQF/Bt4TzrBCf.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter-Medium",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-MediumItalic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/khkJkwSL66WFg8SX6Wa726c.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/0E7IMbDzcGABpBwwqNEt60wU0w.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JEXmejW8mXOYMtt0hyRg811kHac.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ksvR4VsLksjpSwnC2fPgHRNMw.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	`.framer-TngR9 .framer-styles-preset-n2ro6t:not(.rich-text-wrapper), .framer-TngR9 .framer-styles-preset-n2ro6t.rich-text-wrapper h4 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -1.7px; --framer-line-height: 1.4em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, #0a0a0a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 768px) { .framer-TngR9 .framer-styles-preset-n2ro6t:not(.rich-text-wrapper), .framer-TngR9 .framer-styles-preset-n2ro6t.rich-text-wrapper h4 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 30px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -1.7px; --framer-line-height: 1.4em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, #0a0a0a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 767px) and (min-width: 0px) { .framer-TngR9 .framer-styles-preset-n2ro6t:not(.rich-text-wrapper), .framer-TngR9 .framer-styles-preset-n2ro6t.rich-text-wrapper h4 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -1.7px; --framer-line-height: 1.4em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, #0a0a0a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className3 = "framer-TngR9";

// /:https://framerusercontent.com/modules/eYxcfZOJG8jPXs55MBP2/MEKfHEGAyzkSVpEGM0Ev/Uz9I2MGYn.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"Inter-Medium",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css4 = [
	`.framer-cCdlU .framer-styles-preset-a20fug:not(.rich-text-wrapper), .framer-cCdlU .framer-styles-preset-a20fug.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.7em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, #0a0a0a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className4 = "framer-cCdlU";

// /:https://framerusercontent.com/modules/lBjvaD1vgY1QcfP7eFDb/4enrAyLpmrSVkNXwbdyj/dQ3AE0SgG.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/5pudDCW3pau8YED9N5dD/8QKv8xvLgTMilE5SXW45/qoAsAPurP.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css5 = [
	`.framer-R44MM .framer-styles-preset-c8zt5i:not(.rich-text-wrapper), .framer-R44MM .framer-styles-preset-c8zt5i.rich-text-wrapper p { --framer-font-family: "Inter", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.7em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, #0a0a0a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className5 = "framer-R44MM";

// /:https://framerusercontent.com/modules/lBjvaD1vgY1QcfP7eFDb/4enrAyLpmrSVkNXwbdyj/dQ3AE0SgG.js
var cycleOrder = ["Z4q0_cGi4", "Rk08c3bim"];
var serializationHash = "framer-lYv7P";
var variantClassNames = {
	Rk08c3bim: "framer-v-1pwk485",
	Z4q0_cGi4: "framer-v-1okoed",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "Z4q0_cGi4",
	Phone: "Rk08c3bim",
};
var getProps = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		H5Zj31Y5I: text ?? props.H5Zj31Y5I ?? "Smart CRM",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Z4q0_cGi4",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		H5Zj31Y5I,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Z4q0_cGi4",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className5];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1okoed",
							className6,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Z4q0_cGi4"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-6bd91969-2aed-44fe-99ae-751a977f8387, rgba(59, 59, 59, 0.12))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-edb75272-7804-467f-a20f-44bba7f8a130, rgb(255, 255, 255))",
							borderBottomLeftRadius: 19,
							borderBottomRightRadius: 19,
							borderTopLeftRadius: 19,
							borderTopRightRadius: 19,
							...style,
						}}
						{...addPropertyOverrides(
							{
								Rk08c3bim: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-tx5ocg"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"fdtDGFLbY"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, rgb(10, 10, 10))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={H5Zj31Y5I}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									Rk08c3bim: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-c8zt5i"}
													data-styles-preset={"qoAsAPurP"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, rgb(10, 10, 10)))",
													}}
												>
													{"Smart CRM"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-10vu81k"}
									data-styles-preset={"E1ztKgsMN"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, rgb(10, 10, 10)))",
									}}
								>
									{"Smart CRM"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lYv7P.framer-3nc9zs, .framer-lYv7P .framer-3nc9zs { display: block; }",
	".framer-lYv7P.framer-1okoed { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 5px 16px 5px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-lYv7P .framer-tx5ocg { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css2,
	...css5,
	'.framer-lYv7P[data-border="true"]::after, .framer-lYv7P [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerdQ3AE0SgG = withCSS(Component, css6, "framer-lYv7P");
var stdin_default = FramerdQ3AE0SgG;
FramerdQ3AE0SgG.displayName = "Feature Tag";
FramerdQ3AE0SgG.defaultProps = {
	height: 37.2,
	width: 118.517,
};
addPropertyControls(FramerdQ3AE0SgG, {
	variant: {
		options: ["Z4q0_cGi4", "Rk08c3bim"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	H5Zj31Y5I: {
		defaultValue: "Smart CRM",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerdQ3AE0SgG,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts5),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/ZqeR0xJIQSkteerOkJ6f/uMqreds5uf3jmT8eMTMM/TeA9qhnZ8.js
var RichTextWithFX = withFX(RichText2);
var FeatureTagFonts = getFonts(stdin_default);
var ImageWithFX = withFX(Image);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var MotionDivWithFX = withFX(motion2.div);
var cycleOrder2 = ["dPWVGVeNz", "k8GOL4EQD", "fwzFVfYIM"];
var serializationHash2 = "framer-2ISTH";
var variantClassNames2 = {
	dPWVGVeNz: "framer-v-1jcqi8b",
	fwzFVfYIM: "framer-v-19bt7pz",
	k8GOL4EQD: "framer-v-1y3i004",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 50,
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1.2,
	stiffness: 400,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: -100,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 100,
	y: 0,
};
var transition3 = {
	damping: 60,
	delay: 0.2,
	mass: 1.2,
	stiffness: 400,
	type: "spring",
};
var inertia = {
	bounceDamping: 60,
	bounceStiffness: 400,
	delay: 0,
	type: "inertia",
};
var preventDefault = (e) => e.preventDefault();
var animation3 = {
	cursor: "grabbing",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "dPWVGVeNz",
	Phone: "fwzFVfYIM",
	Tablet: "k8GOL4EQD",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "dPWVGVeNz",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "dPWVGVeNz",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className, className4, className3];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1jcqi8b",
							className6,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"dPWVGVeNz"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								fwzFVfYIM: {
									"data-framer-name": "Phone",
								},
								k8GOL4EQD: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-tak3wg"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"khr0g5VxB"}
						>
							<motion2.div
								className={"framer-axw17f"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"VoapUFsgV"}
							>
								<RichTextWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-k93wt2"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Z41aK2Esk"}
									style={{
										"--extracted-1of0zx5":
											"var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, rgb(10, 10, 10))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.h2
											className={"framer-styles-preset-arh37p"}
											data-styles-preset={"SQ5YpA5LL"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-2d5ebd3e-c4d8-4b51-bbfd-da37d69b294f, rgb(10, 10, 10)))",
											}}
										>
											{"Grow 10x faster than your competitors"}
										</motion2.h2>
									</React2.Fragment>
								</RichTextWithFX>
							</motion2.div>
							<motion2.div
								className={"framer-13uwmoo"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"T4tebrUZ4"}
							>
								<ImageWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "BG",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0,
										),
										pixelHeight: 1232,
										pixelWidth: 1020,
										sizes: `max((min(min(max(${componentViewport?.width || "100vw"} - 60px, 1px), 1200px), 1040px) - 24px) / 2, 1px)`,
										src: "https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?width=1020&height=1232",
										srcSet:
											"https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?scale-down-to=1024&width=1020&height=1232 847w,https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?width=1020&height=1232 1020w",
									}}
									className={"framer-175ssrc"}
									data-framer-name={"Content Left"}
									layoutDependency={layoutDependency}
									layoutId={"bwQIwQIPc"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
									{...addPropertyOverrides2(
										{
											fwzFVfYIM: {
												background: {
													alt: "BG",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															0,
													),
													pixelHeight: 1232,
													pixelWidth: 1020,
													sizes: `min(max(${componentViewport?.width || "100vw"} - 40px, 1px), ${componentViewport?.width || "100vw"} - 40px)`,
													src: "https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?width=1020&height=1232",
													srcSet:
														"https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?scale-down-to=1024&width=1020&height=1232 847w,https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?width=1020&height=1232 1020w",
												},
											},
											k8GOL4EQD: {
												background: {
													alt: "BG",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															0,
													),
													pixelHeight: 1232,
													pixelWidth: 1020,
													sizes: `min(min(max(${componentViewport?.width || "100vw"} - 60px, 1px), ${componentViewport?.width || "100vw"} - 60px), 550px)`,
													src: "https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?width=1020&height=1232",
													srcSet:
														"https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?scale-down-to=1024&width=1020&height=1232 847w,https://framerusercontent.com/images/WQSAYXQUyQPpBmLvIk3Eem8UhxU.png?width=1020&height=1232 1020w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-kf4aja"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"EkBFN98ik"}
									>
										<motion2.div
											className={"framer-2osdi8"}
											data-framer-name={"Tag"}
											layoutDependency={layoutDependency}
											layoutId={"nXMx7LnO4"}
										>
											<Image
												background={{
													alt: "Icon",
													fit: "fit",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(64 +
																((componentViewport?.height || 200) -
																	64 -
																	621.4) /
																	2) +
															0 +
															121.6 +
															0 +
															57 +
															0 +
															0 +
															0 +
															1,
													),
													pixelHeight: 32,
													pixelWidth: 32,
													positionX: "center",
													positionY: "center",
													src: "https://framerusercontent.com/images/R8hjhXhCWr2pojFiHwRyeSzgU8.svg?width=32&height=32",
												}}
												className={"framer-117epnl"}
												layoutDependency={layoutDependency}
												layoutId={"LzrBVZaMo"}
												{...addPropertyOverrides2(
													{
														fwzFVfYIM: {
															background: {
																alt: "Icon",
																fit: "fit",
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		(60 +
																			((componentViewport?.height || 200) -
																				60 -
																				937.4) /
																				2) +
																		0 +
																		97.6 +
																		0 +
																		0 +
																		20 +
																		0 +
																		0 +
																		0 +
																		1,
																),
																pixelHeight: 32,
																pixelWidth: 32,
																positionX: "center",
																positionY: "center",
																src: "https://framerusercontent.com/images/R8hjhXhCWr2pojFiHwRyeSzgU8.svg?width=32&height=32",
															},
														},
														k8GOL4EQD: {
															background: {
																alt: "Icon",
																fit: "fit",
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		(80 +
																			((componentViewport?.height || 200) -
																				80 -
																				1243.4) /
																				2) +
																		0 +
																		119.6 +
																		0 +
																		0 +
																		57 +
																		0 +
																		0 +
																		0 +
																		1,
																),
																pixelHeight: 32,
																pixelWidth: 32,
																positionX: "center",
																positionY: "center",
																src: "https://framerusercontent.com/images/R8hjhXhCWr2pojFiHwRyeSzgU8.svg?width=32&height=32",
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
											<RichText2
												__fromCanvasComponent={true}
												className={"framer-1y10k2r"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"OE6UjKwOE"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-edb75272-7804-467f-a20f-44bba7f8a130, rgb(255, 255, 255))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-a20fug"}
														data-styles-preset={"Uz9I2MGYn"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-edb75272-7804-467f-a20f-44bba7f8a130, rgb(255, 255, 255)))",
														}}
													>
														{"AI Assist"}
													</motion2.p>
												</React2.Fragment>
											</RichText2>
										</motion2.div>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-xgh7wm"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"YnnqUMX9u"}
											style={{
												"--extracted-1eung3n":
													"var(--token-edb75272-7804-467f-a20f-44bba7f8a130, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.h4
													className={"framer-styles-preset-n2ro6t"}
													data-styles-preset={"Bt4TzrBCf"}
													style={{
														"--framer-text-color":
															"var(--extracted-1eung3n, var(--token-edb75272-7804-467f-a20f-44bba7f8a130, rgb(255, 255, 255)))",
													}}
												>
													{
														"Keep up the momentum! Sales are up 86% compared to last week"
													}
												</motion2.h4>
											</React2.Fragment>
										</RichText2>
									</motion2.div>
									<motion2.div
										className={"framer-1vygaj9"}
										data-framer-name={"Bottom"}
										layoutDependency={layoutDependency}
										layoutId={"hWM3xiXE2"}
									>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												258.8 +
												0 +
												0
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															0 +
															20 +
															192.8 +
															0 +
															0,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															0 +
															57 +
															258.8 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1fshxfd-container"}
												layoutDependency={layoutDependency}
												layoutId={"e649hUwmp-container"}
												nodeId={"e649hUwmp"}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "Generate summary",
													height: "100%",
													id: "e649hUwmp",
													layoutId: "e649hUwmp",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												258.8 +
												0 +
												45
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															0 +
															20 +
															192.8 +
															0 +
															45,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															0 +
															57 +
															258.8 +
															0 +
															45,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-v4bqdg-container"}
												layoutDependency={layoutDependency}
												layoutId={"RJd8023o8-container"}
												nodeId={"RJd8023o8"}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "How to increase sales next week?",
													height: "100%",
													id: "RJd8023o8",
													layoutId: "RJd8023o8",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												258.8 +
												0 +
												90
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															0 +
															20 +
															192.8 +
															0 +
															90,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															0 +
															57 +
															258.8 +
															0 +
															90,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-12ggoog-container"}
												layoutDependency={layoutDependency}
												layoutId={"YbGQW0S9q-container"}
												nodeId={"YbGQW0S9q"}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "What the item should we ewduce?",
													height: "100%",
													id: "YbGQW0S9q",
													layoutId: "YbGQW0S9q",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion2.div>
								</ImageWithFX>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition3,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation2}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-17w99fp"}
									data-framer-name={"Content Right"}
									layoutDependency={layoutDependency}
									layoutId={"YhJDR4hZa"}
									style={{
										backgroundColor:
											"var(--token-edb75272-7804-467f-a20f-44bba7f8a130, rgb(255, 255, 255))",
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
								>
									<motion2.div
										className={"framer-ibf318"}
										data-framer-name={"Image Wrapper"}
										layoutDependency={layoutDependency}
										layoutId={"WA3gxdHiW"}
									>
										<Image
											background={{
												alt: "image",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(64 +
															((componentViewport?.height || 200) -
																64 -
																621.4) /
																2) +
														0 +
														121.6 +
														0 +
														57 +
														92.9 +
														0,
												),
												pixelHeight: 801,
												pixelWidth: 800,
												sizes: "199px",
												src: "https://framerusercontent.com/images/wxABU3HkQWBTINiagoFuc2YLBiM.png?width=800&height=801",
												srcSet:
													"https://framerusercontent.com/images/wxABU3HkQWBTINiagoFuc2YLBiM.png?width=800&height=801 800w",
											}}
											className={"framer-xqjlrd"}
											layoutDependency={layoutDependency}
											layoutId={"hzR00U4ru"}
											style={{
												borderBottomLeftRadius: 40,
												borderBottomRightRadius: 40,
												borderTopLeftRadius: 40,
												borderTopRightRadius: 40,
											}}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														background: {
															alt: "image",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	(60 +
																		((componentViewport?.height || 200) -
																			60 -
																			937.4) /
																			2) +
																	0 +
																	97.6 +
																	0 +
																	379.8 +
																	0 +
																	130 +
																	0,
															),
															pixelHeight: 801,
															pixelWidth: 800,
															sizes: "199px",
															src: "https://framerusercontent.com/images/wxABU3HkQWBTINiagoFuc2YLBiM.png?width=800&height=801",
															srcSet:
																"https://framerusercontent.com/images/wxABU3HkQWBTINiagoFuc2YLBiM.png?width=800&height=801 800w",
														},
													},
													k8GOL4EQD: {
														background: {
															alt: "image",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	(80 +
																		((componentViewport?.height || 200) -
																			80 -
																			1243.4) /
																			2) +
																	0 +
																	119.6 +
																	0 +
																	523.8 +
																	0 +
																	200 +
																	0,
															),
															pixelHeight: 801,
															pixelWidth: 800,
															sizes: "199px",
															src: "https://framerusercontent.com/images/wxABU3HkQWBTINiagoFuc2YLBiM.png?width=800&height=801",
															srcSet:
																"https://framerusercontent.com/images/wxABU3HkQWBTINiagoFuc2YLBiM.png?width=800&height=801 800w",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												92.9 +
												-12.99
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															379.8 +
															0 +
															130 +
															-15.08,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															523.8 +
															0 +
															200 +
															-12.99,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-12sm9an-container"}
												drag={true}
												dragMomentum={true}
												dragSnapToOrigin={true}
												dragTransition={inertia}
												layoutDependency={layoutDependency}
												layoutId={"o94WlBIZO-container"}
												nodeId={"o94WlBIZO"}
												onMouseDown={preventDefault}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
												style={{
													rotate: -18,
												}}
												whileTap={animation3}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "Sales automation",
													height: "100%",
													id: "o94WlBIZO",
													layoutId: "o94WlBIZO",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												92.9 +
												200 -
												-61
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															379.8 +
															0 +
															130 +
															200 -
															-59,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															523.8 +
															0 +
															200 +
															200 -
															-61,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-pory8-container"}
												drag={true}
												dragMomentum={true}
												dragSnapToOrigin={true}
												dragTransition={inertia}
												layoutDependency={layoutDependency}
												layoutId={"JOAOQ_MEb-container"}
												nodeId={"JOAOQ_MEb"}
												onMouseDown={preventDefault}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
												transformTemplate={transformTemplate1}
												whileTap={animation3}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "Customer insights",
													height: "100%",
													id: "JOAOQ_MEb",
													layoutId: "JOAOQ_MEb",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												92.9 +
												200 -
												-21.041
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															379.8 +
															0 +
															130 +
															200 -
															-17.0194,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															523.8 +
															0 +
															200 +
															200 -
															-21.041,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-1386sec-container"}
												drag={true}
												dragMomentum={true}
												dragSnapToOrigin={true}
												dragTransition={inertia}
												layoutDependency={layoutDependency}
												layoutId={"ZADyYQ9b7-container"}
												nodeId={"ZADyYQ9b7"}
												onMouseDown={preventDefault}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
												style={{
													rotate: 17,
												}}
												transformTemplate={transformTemplate1}
												variants={{
													fwzFVfYIM: {
														rotate: 11,
													},
												}}
												whileTap={animation3}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "Workflow",
													height: "100%",
													id: "ZADyYQ9b7",
													layoutId: "ZADyYQ9b7",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												92.9 +
												200 -
												-8.9779
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															379.8 +
															0 +
															130 +
															200 -
															-8.9779,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															523.8 +
															0 +
															200 +
															200 -
															-8.9779,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-16kq63a-container"}
												drag={true}
												dragMomentum={true}
												dragSnapToOrigin={true}
												dragTransition={inertia}
												layoutDependency={layoutDependency}
												layoutId={"TF1wl9wTs-container"}
												nodeId={"TF1wl9wTs"}
												onMouseDown={preventDefault}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
												style={{
													rotate: 7,
												}}
												transformTemplate={transformTemplate1}
												whileTap={animation3}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "Time saving",
													height: "100%",
													id: "TF1wl9wTs",
													layoutId: "TF1wl9wTs",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												92.9 +
												-82.0277
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															379.8 +
															0 +
															130 +
															-81.9803,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															523.8 +
															0 +
															200 +
															-82.0277,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-tphhl3-container"}
												drag={true}
												dragMomentum={true}
												dragSnapToOrigin={true}
												dragTransition={inertia}
												layoutDependency={layoutDependency}
												layoutId={"Wxu4Iqe8S-container"}
												nodeId={"Wxu4Iqe8S"}
												onMouseDown={preventDefault}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
												style={{
													rotate: 7,
												}}
												transformTemplate={transformTemplate1}
												whileTap={animation3}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "Smart CRM",
													height: "100%",
													id: "Wxu4Iqe8S",
													layoutId: "Wxu4Iqe8S",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={37}
											y={
												(componentViewport?.y || 0) +
												(64 +
													((componentViewport?.height || 200) - 64 - 621.4) /
														2) +
												0 +
												121.6 +
												0 +
												57 +
												92.9 +
												-32.0058
											}
											{...addPropertyOverrides2(
												{
													fwzFVfYIM: {
														y:
															(componentViewport?.y || 0) +
															(60 +
																((componentViewport?.height || 200) -
																	60 -
																	937.4) /
																	2) +
															0 +
															97.6 +
															0 +
															379.8 +
															0 +
															130 +
															-32.0052,
													},
													k8GOL4EQD: {
														y:
															(componentViewport?.y || 0) +
															(80 +
																((componentViewport?.height || 200) -
																	80 -
																	1243.4) /
																	2) +
															0 +
															119.6 +
															0 +
															523.8 +
															0 +
															200 +
															-32.0058,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-mle63m-container"}
												drag={true}
												dragMomentum={true}
												dragSnapToOrigin={true}
												dragTransition={inertia}
												layoutDependency={layoutDependency}
												layoutId={"jRC7VEYQT-container"}
												nodeId={"jRC7VEYQT"}
												onMouseDown={preventDefault}
												rendersWithMotion={true}
												scopeId={"TeA9qhnZ8"}
												style={{
													rotate: 4,
												}}
												whileTap={animation3}
											>
												{_jsx2(stdin_default, {
													H5Zj31Y5I: "Sales efficiency",
													height: "100%",
													id: "jRC7VEYQT",
													layoutId: "jRC7VEYQT",
													variant: "Z4q0_cGi4",
													width: "100%",
													...addPropertyOverrides2(
														{
															fwzFVfYIM: {
																variant: "Rk08c3bim",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
									</motion2.div>
								</MotionDivWithFX>
							</motion2.div>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-2ISTH.framer-uwlk63, .framer-2ISTH .framer-uwlk63 { display: block; }",
	".framer-2ISTH.framer-1jcqi8b { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 64px 30px 0px 30px; position: relative; width: 1200px; }",
	".framer-2ISTH .framer-tak3wg { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-2ISTH .framer-axw17f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-2ISTH .framer-k93wt2 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-2ISTH .framer-13uwmoo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 1040px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-2ISTH .framer-175ssrc { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 166px; height: min-content; justify-content: center; overflow: hidden; padding: 57px 95px 57px 54px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-2ISTH .framer-kf4aja { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-2ISTH .framer-2osdi8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-2ISTH .framer-117epnl { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); overflow: hidden; position: relative; width: 32px; }",
	".framer-2ISTH .framer-1y10k2r { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-2ISTH .framer-xgh7wm { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-2ISTH .framer-1vygaj9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-2ISTH .framer-1fshxfd-container, .framer-2ISTH .framer-v4bqdg-container, .framer-2ISTH .framer-12ggoog-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-2ISTH .framer-17w99fp { align-content: center; align-items: center; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 166px; height: auto; justify-content: center; overflow: hidden; padding: 57px 95px 57px 54px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-2ISTH .framer-ibf318 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-2ISTH .framer-xqjlrd { flex: none; height: 200px; overflow: hidden; position: relative; width: 199px; will-change: var(--framer-will-change-override, transform); }",
	".framer-2ISTH .framer-12sm9an-container { cursor: grab; flex: none; height: auto; left: -93px; position: absolute; top: -13px; width: auto; z-index: 3; }",
	".framer-2ISTH .framer-pory8-container { bottom: -98px; cursor: grab; flex: none; height: auto; left: 55%; position: absolute; width: auto; z-index: 3; }",
	".framer-2ISTH .framer-1386sec-container { bottom: -58px; cursor: grab; flex: none; height: auto; left: 110%; position: absolute; width: auto; z-index: 3; }",
	".framer-2ISTH .framer-16kq63a-container { bottom: -46px; cursor: grab; flex: none; height: auto; left: 10%; position: absolute; width: auto; z-index: 3; }",
	".framer-2ISTH .framer-tphhl3-container { cursor: grab; flex: none; height: auto; left: 53%; position: absolute; top: -82px; width: auto; z-index: 3; }",
	".framer-2ISTH .framer-mle63m-container { cursor: grab; flex: none; height: auto; position: absolute; right: -69px; top: -32px; width: auto; z-index: 3; }",
	".framer-2ISTH.framer-v-1y3i004.framer-1jcqi8b { padding: 80px 30px 0px 30px; width: 768px; }",
	".framer-2ISTH.framer-v-1y3i004 .framer-tak3wg { gap: 62px 56px; max-width: 100%; }",
	".framer-2ISTH.framer-v-1y3i004 .framer-13uwmoo { flex-direction: column; max-width: 550px; }",
	".framer-2ISTH.framer-v-1y3i004 .framer-175ssrc { flex: none; width: 100%; }",
	".framer-2ISTH.framer-v-1y3i004 .framer-17w99fp { align-self: unset; aspect-ratio: 0.8333333333333334 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 240px); padding: 0px; width: 100%; }",
	".framer-2ISTH.framer-v-19bt7pz.framer-1jcqi8b { overflow: visible; padding: 60px 20px 0px 20px; width: 390px; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-tak3wg { gap: 40px; max-width: 100%; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-13uwmoo { flex-direction: column; gap: 20px; max-width: 100%; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-175ssrc { flex: none; gap: 100px; padding: 20px; width: 100%; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-17w99fp { align-self: unset; aspect-ratio: 0.7608695652173914 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 263px); padding: 0px; width: 100%; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-xqjlrd { aspect-ratio: 0.995 / 1; height: var(--framer-aspect-ratio-supported, 200px); }",
	".framer-2ISTH.framer-v-19bt7pz .framer-12sm9an-container { left: -55px; top: -15px; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-pory8-container { bottom: -96px; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-1386sec-container { bottom: -54px; left: 101%; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-tphhl3-container { top: -82px; }",
	".framer-2ISTH.framer-v-19bt7pz .framer-mle63m-container { right: -59px; top: -32px; }",
	...css,
	...css4,
	...css3,
];
var FramerTeA9qhnZ8 = withCSS2(Component2, css7, "framer-2ISTH");
var stdin_default2 = FramerTeA9qhnZ8;
FramerTeA9qhnZ8.displayName = "Grow section";
FramerTeA9qhnZ8.defaultProps = {
	height: 776,
	width: 1200,
};
addPropertyControls2(FramerTeA9qhnZ8, {
	variant: {
		options: ["dPWVGVeNz", "k8GOL4EQD", "fwzFVfYIM"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerTeA9qhnZ8,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FeatureTagFonts,
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts4),
		...getFontsFromSharedStyle2(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:grow-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "fwzFVfYIM",
	md: "k8GOL4EQD",
	xl: "dPWVGVeNz",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1f8016c2711a0971d3886a1fa86603a272ebed9610aab253ce8e056bfbcc56d1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GrowSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1f8016c2711a0971d3886a1fa86603a272ebed9610aab253ce8e056bfbcc56d1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var grow_section_default = ComponentWithRoot;
export { grow_section_default as default };
