// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ac4b2f1e7a67ec54 "Alytics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-43AO5CDN.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import { stdin_default } from "./chunks/chunk-KYLAGT6A.js";
import "./chunks/chunk-XAKJVEAV.js";
import "./chunks/chunk-JCMURR45.js";
import { className, css, fonts } from "./chunks/chunk-T7ZDJKBY.js";
import { routes } from "./chunks/chunk-D3NEX6SN.js";

// virtual:benefits
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vI82SBiPMzKOKGKXR04Q/4qF93HmGTniLC7UHaibj/Mhdt7N05x.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/eR1NwOo4ektVkHHQ7wlp/qjLd1fH96rRoyCHiVddP/xQZOhxz9O.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var PhosphorControls = getPropertyControls(Icon);
var serializationHash = "framer-sdDEX";
var variantClassNames = {
	PUx2RS3qv: "framer-v-17cm7ho",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, icon, id, text, title, width, ...props }) => {
	return {
		...props,
		L9gne9eZL: title ?? props.L9gne9eZL ?? "Real-Time Tracking",
		VaH90uGRr: icon ?? props.VaH90uGRr ?? "Clock",
		wLIkGyPV4:
			text ??
			props.wLIkGyPV4 ??
			"See your key metrics update instantly, so you can act fast.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		VaH90uGRr,
		L9gne9eZL,
		wLIkGyPV4,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "PUx2RS3qv",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17cm7ho",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"PUx2RS3qv"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							boxShadow: "0px 1px 20px 0px rgba(0, 0, 0, 0.03)",
							...style,
						}}
					>
						<motion.div
							className={"framer-1w98ndk"}
							data-framer-name={"Icon container"}
							layoutDependency={layoutDependency}
							layoutId={"AfJBDI8PV"}
							style={{
								backgroundColor:
									"var(--token-563968fe-1dc6-43a4-93e9-d9bd53c68cc8, rgb(225, 234, 248))",
								borderBottomLeftRadius: 6,
								borderBottomRightRadius: 6,
								borderTopLeftRadius: 6,
								borderTopRightRadius: 6,
								boxShadow:
									"0px 0.6021873017743928px 0.6021873017743928px -1px rgba(18, 109, 251, 0.15), 0px 2.288533303243457px 2.288533303243457px -2px rgba(18, 109, 251, 0.14), 0px 10px 10px -3px rgba(18, 109, 251, 0.1)",
							}}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-mtslt3-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"S4ExvBQKJ-container"}
									nodeId={"S4ExvBQKJ"}
									rendersWithMotion={true}
									scopeId={"xQZOhxz9O"}
								>
									<Icon
										color={
											"var(--token-58f62a67-15de-4e6e-b079-00f80c0704c1, rgb(18, 109, 251))"
										}
										height={"100%"}
										iconSearch={"House"}
										iconSelection={VaH90uGRr}
										id={"S4ExvBQKJ"}
										layoutId={"S4ExvBQKJ"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"fill"}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						<motion.div
							className={"framer-x2em0o"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"i3Nzl1z03"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1s95sjl"}
								data-framer-name={"Heading"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"AyLjg9iB3"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={L9gne9eZL}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h5
										className={"framer-styles-preset-ob6p3i"}
										data-styles-preset={"uDzEgMsNq"}
									>
										{"Real-Time Tracking"}
									</motion.h5>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-wf7olw"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"VEsd3Uip_"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={wLIkGyPV4}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-oo9bt8"}
										data-styles-preset={"Qd8jNwk_8"}
									>
										{
											"See your key metrics update instantly, so you can act fast."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-sdDEX.framer-1dr9x67, .framer-sdDEX .framer-1dr9x67 { display: block; }",
	".framer-sdDEX.framer-17cm7ho { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 20px 20px 24px 20px; position: relative; width: 100%; max-width: 355px; will-change: var(--framer-will-change-override, transform); }",
	".framer-sdDEX .framer-1w98ndk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 6px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-sdDEX .framer-mtslt3-container { flex: none; height: 28px; position: relative; width: 28px; }",
	".framer-sdDEX .framer-x2em0o { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-sdDEX .framer-1s95sjl, .framer-sdDEX .framer-wf7olw { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@media (max-width: 768px) { .framer-sdDEX.framer-17cm7ho { padding: 16px 16px 20px 16px; gap: 16px; } }",
	"@media (max-width: 480px) { .framer-sdDEX.framer-17cm7ho { padding: 12px 12px 16px 12px; gap: 12px; } }",
	"@media (max-width: 480px) { .framer-sdDEX .framer-x2em0o { gap: 6px; } }",
	...css2,
	...css,
];
var FramerxQZOhxz9O = withCSS(Component, css3, "framer-sdDEX");
var stdin_default2 = FramerxQZOhxz9O;
FramerxQZOhxz9O.displayName = "Benefit Card";
FramerxQZOhxz9O.defaultProps = {
	height: 201,
	width: 355,
};
addPropertyControls(FramerxQZOhxz9O, {
	VaH90uGRr: PhosphorControls?.["iconSelection"] && {
		...PhosphorControls["iconSelection"],
		defaultValue: "Clock",
		description: void 0,
		hidden: void 0,
		title: "Icon",
	},
	L9gne9eZL: {
		defaultValue: "Real-Time Tracking",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	wLIkGyPV4: {
		defaultValue: "See your key metrics update instantly, so you can act fast.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerxQZOhxz9O,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/vI82SBiPMzKOKGKXR04Q/4qF93HmGTniLC7UHaibj/Mhdt7N05x.js
var SeperatorFonts = getFonts2(stdin_default);
var BenefitCardFonts = getFonts2(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(
	SmartComponentScopedContainer2,
);
var MotionDivWithFX = withFX(motion2.div);
var cycleOrder = ["Jn3wngbgL", "odseAt3OQ"];
var serializationHash2 = "framer-NjDvc";
var variantClassNames2 = {
	Jn3wngbgL: "framer-v-1cqaqy6",
	odseAt3OQ: "framer-v-1wyepbq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 60,
	delay: 0.1,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition3 = {
	damping: 60,
	delay: 0.2,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition4 = {
	damping: 60,
	delay: 0.3,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "Jn3wngbgL",
	"Variant 2": "odseAt3OQ",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Jn3wngbgL",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "Jn3wngbgL",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1cqaqy6",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Jn3wngbgL"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								odseAt3OQ: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1fhojz8"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"xY4OLg1Zx"}
						>
							<ComponentViewportProvider2
								height={207}
								width={`calc(min(${componentViewport?.width || "100vw"}, 1200px) - 96px)`}
								y={
									(componentViewport?.y || 0) +
									100 +
									(((componentViewport?.height || 900) - 200 - 685) / 2 +
										0 +
										0) +
									0 +
									0
								}
								{...addPropertyOverrides(
									{
										odseAt3OQ: {
											width: `calc(min(${componentViewport?.width || "100vw"}, 390px) - 96px)`,
											y:
												(componentViewport?.y || 0) +
												100 +
												(((componentViewport?.height || 1924) - 200 - 1607) /
													2 +
													0 +
													0) +
												19 +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer2
									className={"framer-w35o6l-container"}
									layoutDependency={layoutDependency}
									layoutId={"z2HQmusEp-container"}
									nodeId={"z2HQmusEp"}
									rendersWithMotion={true}
									scopeId={"Mhdt7N05x"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "z2HQmusEp",
										layoutId: "z2HQmusEp",
										LZ8_yaAGB: "Benefits That Save You Time, Money, and Stress",
										style: {
											width: "100%",
										},
										sWnc4R5C9:
											"Monitor metrics as they happen, so you can respond quickly and keep your goals on track.",
										variant: "GCevxSqGm",
										width: "100%",
										ZBMvVPx0w: "Why Choose Ai2Market?",
									})}
								</SmartComponentScopedContainer2>
							</ComponentViewportProvider2>
							<motion2.div
								className={"framer-16oiovg"}
								data-framer-name={"Cards"}
								layoutDependency={layoutDependency}
								layoutId={"dn1mjbsbx"}
							>
								<motion2.div
									className={"framer-1h86pdy"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"Z_fCILPw3"}
								>
									<ComponentViewportProvider2
										height={201}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 900) - 200 - 685) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												odseAt3OQ: {
													width: `calc(min(${componentViewport?.width || "100vw"}, 390px) - 96px)`,
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 1924) -
															200 -
															1607) /
															2 +
															0 +
															0) +
														19 +
														263 +
														0 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-nd6jpz-container"}
											layoutDependency={layoutDependency}
											layoutId={"FWFNKc4Hh-container"}
											nodeId={"FWFNKc4Hh"}
											rendersWithMotion={true}
											scopeId={"Mhdt7N05x"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "FWFNKc4Hh",
												L9gne9eZL: "Real-Time Tracking",
												layoutId: "FWFNKc4Hh",
												style: {
													width: "100%",
												},
												VaH90uGRr: "Clock",
												width: "100%",
												wLIkGyPV4:
													"Monitor activity instantly, reducing decision-making time by 40% for smarter business moves.",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={201}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 900) - 200 - 685) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												odseAt3OQ: {
													width: `calc(min(${componentViewport?.width || "100vw"}, 390px) - 96px)`,
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 1924) -
															200 -
															1607) /
															2 +
															0 +
															0) +
														19 +
														263 +
														0 +
														0 +
														0 +
														221,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-leh0yf-container"}
											layoutDependency={layoutDependency}
											layoutId={"KkiA_A86a-container"}
											nodeId={"KkiA_A86a"}
											rendersWithMotion={true}
											scopeId={"Mhdt7N05x"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "KkiA_A86a",
												L9gne9eZL: "24/7 Support",
												layoutId: "KkiA_A86a",
												style: {
													width: "100%",
												},
												VaH90uGRr: "DeviceTablet",
												width: "100%",
												wLIkGyPV4:
													"Enjoy 99.9% uptime and round-the-clock expert assistance.",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={201}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 900) - 200 - 685) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												odseAt3OQ: {
													width: `calc(min(${componentViewport?.width || "100vw"}, 390px) - 96px)`,
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 1924) -
															200 -
															1607) /
															2 +
															0 +
															0) +
														19 +
														263 +
														0 +
														0 +
														0 +
														442,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition4,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1c1csl8-container"}
											layoutDependency={layoutDependency}
											layoutId={"NYLTELam1-container"}
											nodeId={"NYLTELam1"}
											rendersWithMotion={true}
											scopeId={"Mhdt7N05x"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "NYLTELam1",
												L9gne9eZL: "AI Data-Driven Insights",
												layoutId: "NYLTELam1",
												style: {
													width: "100%",
												},
												VaH90uGRr: "Airplane",
												width: "100%",
												wLIkGyPV4:
													"Uncover growth patterns with AI, boosting business efficiency and performance by 30%.",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider2>
								</motion2.div>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1kgz0ic"}
									data-framer-name={"Bottom"}
									layoutDependency={layoutDependency}
									layoutId={"EY6xSZEt_"}
								>
									<ComponentViewportProvider2
										height={201}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 900) - 200 - 685) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											221 +
											0
										}
										{...addPropertyOverrides(
											{
												odseAt3OQ: {
													width: `calc(min(${componentViewport?.width || "100vw"}, 390px) - 96px)`,
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 1924) -
															200 -
															1607) /
															2 +
															0 +
															0) +
														19 +
														263 +
														0 +
														663 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1657vug-container"}
											layoutDependency={layoutDependency}
											layoutId={"S9TfW9CmL-container"}
											nodeId={"S9TfW9CmL"}
											rendersWithMotion={true}
											scopeId={"Mhdt7N05x"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "S9TfW9CmL",
												L9gne9eZL: "Secure Data",
												layoutId: "S9TfW9CmL",
												style: {
													width: "100%",
												},
												VaH90uGRr: "Lock",
												width: "100%",
												wLIkGyPV4:
													"Protect data with enterprise-grade encryption and 100% compliance.",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={201}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 900) - 200 - 685) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											221 +
											0
										}
										{...addPropertyOverrides(
											{
												odseAt3OQ: {
													width: `calc(min(${componentViewport?.width || "100vw"}, 390px) - 96px)`,
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 1924) -
															200 -
															1607) /
															2 +
															0 +
															0) +
														19 +
														263 +
														0 +
														663 +
														0 +
														221,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1wsvqf0-container"}
											layoutDependency={layoutDependency}
											layoutId={"rbfST_9WP-container"}
											nodeId={"rbfST_9WP"}
											rendersWithMotion={true}
											scopeId={"Mhdt7N05x"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "rbfST_9WP",
												L9gne9eZL: "Faster Time to Market",
												layoutId: "rbfST_9WP",
												style: {
													width: "100%",
												},
												VaH90uGRr: "Calendar",
												width: "100%",
												wLIkGyPV4:
													"Launch campaigns 3x faster using AI workflows, accelerating revenue and reducing costly delays.",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider2>
									<ComponentViewportProvider2
										height={201}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 900) - 200 - 685) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											221 +
											0
										}
										{...addPropertyOverrides(
											{
												odseAt3OQ: {
													width: `calc(min(${componentViewport?.width || "100vw"}, 390px) - 96px)`,
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 1924) -
															200 -
															1607) /
															2 +
															0 +
															0) +
														19 +
														263 +
														0 +
														663 +
														0 +
														442,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition4,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-wgj3g6-container"}
											layoutDependency={layoutDependency}
											layoutId={"OHsFB9oYz-container"}
											nodeId={"OHsFB9oYz"}
											rendersWithMotion={true}
											scopeId={"Mhdt7N05x"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "OHsFB9oYz",
												L9gne9eZL: "Custom Automation",
												layoutId: "OHsFB9oYz",
												style: {
													width: "100%",
												},
												VaH90uGRr: "Equals",
												width: "100%",
												wLIkGyPV4:
													"Save 10+ hours weekly with no-code workflows tailored to your unique business needs.",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider2>
								</MotionDivWithFX>
							</motion2.div>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-NjDvc.framer-14p6uvh, .framer-NjDvc .framer-14p6uvh { display: block; }",
	".framer-NjDvc.framer-1cqaqy6 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 0px 100px 0px; position: relative; width: 100%; max-width: 1200px; margin: 0 auto; }",
	".framer-NjDvc .framer-1fhojz8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px 48px 0px 48px; position: relative; width: 100%; }",
	".framer-NjDvc .framer-w35o6l-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-NjDvc .framer-16oiovg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-NjDvc .framer-1h86pdy, .framer-NjDvc .framer-1kgz0ic { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-NjDvc .framer-nd6jpz-container, .framer-NjDvc .framer-leh0yf-container, .framer-NjDvc .framer-1c1csl8-container, .framer-NjDvc .framer-1657vug-container, .framer-NjDvc .framer-1wsvqf0-container, .framer-NjDvc .framer-wgj3g6-container { flex: 1 0 300px; height: auto; position: relative; min-width: 280px; }",
	".framer-NjDvc.framer-v-1wyepbq.framer-1cqaqy6 { width: 100%; max-width: 100%; }",
	".framer-NjDvc.framer-v-1wyepbq .framer-1fhojz8 { max-width: 100%; padding: 19px 16px 19px 16px; }",
	".framer-NjDvc.framer-v-1wyepbq .framer-1h86pdy, .framer-NjDvc.framer-v-1wyepbq .framer-1kgz0ic { flex-direction: column; }",
	".framer-NjDvc.framer-v-1wyepbq .framer-nd6jpz-container, .framer-NjDvc.framer-v-1wyepbq .framer-leh0yf-container, .framer-NjDvc.framer-v-1wyepbq .framer-1c1csl8-container, .framer-NjDvc.framer-v-1wyepbq .framer-1657vug-container, .framer-NjDvc.framer-v-1wyepbq .framer-1wsvqf0-container, .framer-NjDvc.framer-v-1wyepbq .framer-wgj3g6-container { flex: none; width: 100%; }",
	"@media (max-width: 768px) { .framer-NjDvc.framer-1cqaqy6 { padding: 60px 0px 60px 0px; max-width: 100%; } }",
	"@media (max-width: 768px) { .framer-NjDvc .framer-1fhojz8 { padding: 0px 20px 0px 20px; gap: 40px; } }",
	"@media (max-width: 768px) { .framer-NjDvc .framer-1h86pdy, .framer-NjDvc .framer-1kgz0ic { flex-direction: column; gap: 16px; } }",
	"@media (max-width: 768px) { .framer-NjDvc .framer-nd6jpz-container, .framer-NjDvc .framer-leh0yf-container, .framer-NjDvc .framer-1c1csl8-container, .framer-NjDvc .framer-1657vug-container, .framer-NjDvc .framer-1wsvqf0-container, .framer-NjDvc .framer-wgj3g6-container { flex: none; width: 100%; min-width: auto; } }",
	"@media (max-width: 480px) { .framer-NjDvc.framer-1cqaqy6 { padding: 40px 0px 40px 0px; max-width: 100%; } }",
	"@media (max-width: 480px) { .framer-NjDvc .framer-1fhojz8 { padding: 0px 16px 0px 16px; gap: 32px; } }",
];
var FramerMhdt7N05x = withCSS2(Component2, css4, "framer-NjDvc");
var stdin_default3 = FramerMhdt7N05x;
FramerMhdt7N05x.displayName = "Benefits";
FramerMhdt7N05x.defaultProps = {
	height: 900,
	width: 1200,
};
addPropertyControls2(FramerMhdt7N05x, {
	variant: {
		options: ["Jn3wngbgL", "odseAt3OQ"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerMhdt7N05x,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...SeperatorFonts,
		...BenefitCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:benefits
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "odseAt3OQ",
	sm: "odseAt3OQ",
	md: "odseAt3OQ",
	lg: "Jn3wngbgL",
	xl: "Jn3wngbgL",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BenefitsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var benefits_default = ComponentWithRoot;
export { benefits_default as default };
