// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ac4b2f1e7a67ec54 "Alytics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-KYLAGT6A.js";
import "./chunks/chunk-XAKJVEAV.js";
import "./chunks/chunk-JCMURR45.js";
import { className, css, fonts } from "./chunks/chunk-T7ZDJKBY.js";
import { routes } from "./chunks/chunk-D3NEX6SN.js";

// virtual:faq
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/SzUNN0kHl2QaxGOitf7Z/ZfLCjLVJd8d9naXQ8ZT9/lOqyWx384.js
import { jsx as _jsx4, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	ComponentViewportProvider as ComponentViewportProvider2,
	cx as cx3,
	getFonts as getFonts2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef4 } from "react";

// /:https://framerusercontent.com/modules/uX61yGAuuoKjnCR6EZpJ/xYLctqeOcUHIBacOU2a5/GFiJE27cf.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/h8ioHyt4BUxuvVCE1Q10/aTM6mEMGlM19JjX8exDe/AvoidLayoutJumping_Prod.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { useEffect, useRef } from "react";
function AvoidLayoutJumping({ direction, style }) {
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const ref = useRef(null);
	const rafId = useRef();
	const vertical = direction === "vertical" || direction === "both";
	const horizontal = direction === "horizontal" || direction === "both";
	useEffect(() => {
		if (isCanvas) return;
		const parent = ref.current?.parentElement?.parentElement;
		if (!parent) return;
		const container = parent.parentElement;
		if (!container) return;
		const updateSize = () => {
			const rect = parent.getBoundingClientRect();
			if (horizontal) {
				container.style.width = `${rect.width}px`;
			}
			if (vertical) {
				container.style.height = `${rect.height}px`;
			}
			rafId.current = requestAnimationFrame(updateSize);
		};
		rafId.current = requestAnimationFrame(updateSize);
		return () => {
			if (rafId.current) {
				cancelAnimationFrame(rafId.current);
			}
			if (container) {
				if (horizontal) {
					container.style.width = "";
				}
				if (vertical) {
					container.style.height = "";
				}
			}
		};
	}, [direction]);
	return (
		<div
			ref={ref}
			style={{
				...style,
			}}
		/>
	);
}
AvoidLayoutJumping.displayName = "Layout Jump Preventer";
addPropertyControls(AvoidLayoutJumping, {
	direction: {
		type: ControlType.Enum,
		defaultValue: "vertical",
		options: ["vertical", "horizontal", "both"],
		optionTitles: ["Vertical", "Horizontal", "Both"],
		displaySegmentedControl: true,
		segmentedControlDirection: "vertical",
		// @ts-ignore
		optionIcons: [
			"direction-vertical",
			"direction-horizontal",
			"direction-all",
		],
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/fVkAtBELVTlSnVO1efGz/FHHNHxbtS5jgzeSqzCeN/Oqwa7EykX.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/kCCKy3vXKCZ0wxeAxoh6/bef1hY5pCpsv568Uidbg/fzOCHtVId.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;Geist-500", "GF;Geist-700"]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Geist",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geist/v3/gyBhhwUxId8gMGYQMKR3pzfaWI_RruM4mJPby1QNtA.woff2",
				weight: "500",
			},
			{
				family: "Geist",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geist/v3/gyBhhwUxId8gMGYQMKR3pzfaWI_Re-Q4mJPby1QNtA.woff2",
				weight: "700",
			},
		],
	},
];
var css2 = [
	'.framer-a0sUM .framer-styles-preset-17mrwxo:not(.rich-text-wrapper), .framer-a0sUM .framer-styles-preset-17mrwxo.rich-text-wrapper h6 { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Geist", "Geist Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-e1ef367e-e23b-4a9e-826b-77a848c7f0b3, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className2 = "framer-a0sUM";

// /:https://framerusercontent.com/modules/fVkAtBELVTlSnVO1efGz/FHHNHxbtS5jgzeSqzCeN/Oqwa7EykX.js
var cycleOrder = ["slleQ7T1M", "vJmI91GEt"];
var serializationHash = "framer-8ELsP";
var variantClassNames = {
	slleQ7T1M: "framer-v-1hsvecx",
	vJmI91GEt: "framer-v-1koazev",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "slleQ7T1M",
	Open: "vJmI91GEt",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		avByNCwqI: answer ?? props.avByNCwqI ?? "Answer",
		MUYjTPdA0: question ?? props.MUYjTPdA0 ?? "Question",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "slleQ7T1M",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		MUYjTPdA0,
		avByNCwqI,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "slleQ7T1M",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1tfzg1h = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("vJmI91GEt");
	});
	const onTapdygnt2 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("slleQ7T1M");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "vJmI91GEt") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1hsvecx",
							className3,
							classNames,
						)}
						data-framer-name={"Close"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"slleQ7T1M"}
						onTap={onTap1tfzg1h}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow: "0px 1px 20px 0px rgba(0, 0, 0, 0.03)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								vJmI91GEt: {
									"data-framer-name": "Open",
									onTap: onTapdygnt2,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1vh5ryo"}
							data-framer-name={"Question"}
							layoutDependency={layoutDependency}
							layoutId={"ZFRXGuQfC"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1yrl74e"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"hyIUsk7Qk"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={MUYjTPdA0}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-17mrwxo"}
										data-styles-preset={"fzOCHtVId"}
									>
										{"Question"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-7em2pp"}
								data-framer-name={"Plus"}
								layoutDependency={layoutDependency}
								layoutId={"KkOT9qA2X"}
							>
								<motion.div
									className={"framer-6pwctc"}
									layoutDependency={layoutDependency}
									layoutId={"hGnHN40c2"}
									style={{
										backgroundColor:
											"var(--token-e1ef367e-e23b-4a9e-826b-77a848c7f0b3, rgb(0, 0, 0))",
										rotate: 0,
									}}
									variants={{
										vJmI91GEt: {
											rotate: 270,
										},
									}}
								/>
								<motion.div
									className={"framer-1uujxvz"}
									layoutDependency={layoutDependency}
									layoutId={"EYKI2mG3e"}
									style={{
										backgroundColor:
											"var(--token-e1ef367e-e23b-4a9e-826b-77a848c7f0b3, rgb(0, 0, 0))",
										rotate: 90,
									}}
									variants={{
										vJmI91GEt: {
											rotate: 270,
										},
									}}
								/>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-1ywsb0j"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"x3e7OfR52"}
								style={{
									backgroundColor:
										"var(--token-a0d7c77d-bb42-477c-affc-b56f45ae9a8a, rgb(235, 235, 235))",
								}}
							/>
						)}
						{isDisplayed() && (
							<motion.div
								className={"framer-db3x9t"}
								data-framer-name={"Answer"}
								layoutDependency={layoutDependency}
								layoutId={"GHsPVvW2B"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1l62wnk"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"BZOQpShRz"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={avByNCwqI}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-oo9bt8"}
											data-styles-preset={"Qd8jNwk_8"}
										>
											{"Answer"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8ELsP.framer-1mnftlh, .framer-8ELsP .framer-1mnftlh { display: block; }",
	".framer-8ELsP.framer-1hsvecx { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 400px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8ELsP .framer-1vh5ryo, .framer-8ELsP .framer-db3x9t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 16px; position: relative; width: 100%; }",
	".framer-8ELsP .framer-1yrl74e, .framer-8ELsP .framer-1l62wnk { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-8ELsP .framer-7em2pp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 30px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 30px; }",
	".framer-8ELsP .framer-6pwctc, .framer-8ELsP .framer-1uujxvz { flex: none; height: 14px; left: calc(53.33333333333336% - 2px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 14px / 2); width: 2px; z-index: 1; }",
	".framer-8ELsP .framer-1ywsb0j { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; }",
	".framer-8ELsP.framer-v-1koazev .framer-1yrl74e { order: 0; }",
	".framer-8ELsP.framer-v-1koazev .framer-7em2pp { order: 1; }",
	...css2,
	...css,
];
var FramerOqwa7EykX = withCSS(Component, css3, "framer-8ELsP");
var stdin_default2 = FramerOqwa7EykX;
FramerOqwa7EykX.displayName = "FAQ accordion";
FramerOqwa7EykX.defaultProps = {
	height: 62,
	width: 400,
};
addPropertyControls2(FramerOqwa7EykX, {
	variant: {
		options: ["slleQ7T1M", "vJmI91GEt"],
		optionTitles: ["Close", "Open"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	MUYjTPdA0: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question",
		type: ControlType2.String,
	},
	avByNCwqI: {
		defaultValue: "Answer",
		displayTextArea: false,
		title: "Answer",
		type: ControlType2.String,
	},
});
addFonts(
	FramerOqwa7EykX,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/uX61yGAuuoKjnCR6EZpJ/xYLctqeOcUHIBacOU2a5/GFiJE27cf.js
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var FAQAccordionFonts = getFonts(stdin_default2);
var serializationHash2 = "framer-kjRJ3";
var variantClassNames2 = {
	JQ6iOsKki: "framer-v-gbnxqk",
};
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "JQ6iOsKki",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-gbnxqk",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"JQ6iOsKki"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-nnggdl-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"FvDwyaNBw-container"}
								nodeId={"FvDwyaNBw"}
								rendersWithMotion={true}
								scopeId={"GFiJE27cf"}
								transformTemplate={transformTemplate1}
							>
								<AvoidLayoutJumping
									direction={"vertical"}
									height={"100%"}
									id={"FvDwyaNBw"}
									layoutId={"FvDwyaNBw"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={62}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 462) - 0 - 390) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-pmq03y-container"}
								layoutDependency={layoutDependency}
								layoutId={"x7KY3ovGZ-container"}
								nodeId={"x7KY3ovGZ"}
								rendersWithMotion={true}
								scopeId={"GFiJE27cf"}
							>
								{_jsx3(stdin_default2, {
									avByNCwqI:
										"You can deploy your first AI workflow in minutes by selecting from pre-built templates or browsing the marketplace.",
									height: "100%",
									id: "x7KY3ovGZ",
									layoutId: "x7KY3ovGZ",
									MUYjTPdA0: "How quickly can I get started?",
									style: {
										width: "100%",
									},
									variant: "vJmI91GEt",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={62}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 462) - 0 - 390) / 2 + 62 + 20)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-y6szps-container"}
								layoutDependency={layoutDependency}
								layoutId={"r_qwbV18z-container"}
								nodeId={"r_qwbV18z"}
								rendersWithMotion={true}
								scopeId={"GFiJE27cf"}
							>
								{_jsx3(stdin_default2, {
									avByNCwqI:
										"Not at all. AI2Market is built for teams of all sizes. Whether you're in marketing, product, or operations, the interface is intuitive and requires no coding.",
									height: "100%",
									id: "r_qwbV18z",
									layoutId: "r_qwbV18z",
									MUYjTPdA0: "Do I need technical skills to use AI2Market?",
									style: {
										width: "100%",
									},
									variant: "slleQ7T1M",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={62}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 462) - 0 - 390) / 2 + 124 + 40)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1xecb01-container"}
								layoutDependency={layoutDependency}
								layoutId={"myKfRkhEU-container"}
								nodeId={"myKfRkhEU"}
								rendersWithMotion={true}
								scopeId={"GFiJE27cf"}
							>
								{_jsx3(stdin_default2, {
									avByNCwqI:
										"Yes. Ai2Market integrates with CRM, ERP, email, databases, APIs, and 1,500+ apps.",
									height: "100%",
									id: "myKfRkhEU",
									layoutId: "myKfRkhEU",
									MUYjTPdA0: "Can Ai2Market integrate with my existing tools",
									style: {
										width: "100%",
									},
									variant: "slleQ7T1M",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={62}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 462) - 0 - 390) / 2 + 186 + 60)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1b478fp-container"}
								layoutDependency={layoutDependency}
								layoutId={"n0_U88kiY-container"}
								nodeId={"n0_U88kiY"}
								rendersWithMotion={true}
								scopeId={"GFiJE27cf"}
							>
								{_jsx3(stdin_default2, {
									avByNCwqI:
										"Absolutely. We use enterprise-grade encryption and follow best practices in data privacy and compliance.",
									height: "100%",
									id: "n0_U88kiY",
									layoutId: "n0_U88kiY",
									MUYjTPdA0: "Is my data secure on AI2Market?",
									style: {
										width: "100%",
									},
									variant: "slleQ7T1M",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={62}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 462) - 0 - 390) / 2 + 248 + 80)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1f57d4s-container"}
								layoutDependency={layoutDependency}
								layoutId={"gRwuIanIm-container"}
								nodeId={"gRwuIanIm"}
								rendersWithMotion={true}
								scopeId={"GFiJE27cf"}
							>
								{_jsx3(stdin_default2, {
									avByNCwqI:
										"Reduces dependency on multiple SaaS subscriptions. Cuts down manual workforce costs through automation. Provides all-in-one AI solutions under one platform",
									height: "100%",
									id: "gRwuIanIm",
									layoutId: "gRwuIanIm",
									MUYjTPdA0: "How does Ai2Market save me money?",
									style: {
										width: "100%",
									},
									variant: "slleQ7T1M",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kjRJ3.framer-12c79h0, .framer-kjRJ3 .framer-12c79h0 { display: block; }",
	".framer-kjRJ3.framer-gbnxqk { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 720px; }",
	".framer-kjRJ3 .framer-nnggdl-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: auto; z-index: 1; }",
	".framer-kjRJ3 .framer-pmq03y-container, .framer-kjRJ3 .framer-y6szps-container, .framer-kjRJ3 .framer-1xecb01-container, .framer-kjRJ3 .framer-1b478fp-container, .framer-kjRJ3 .framer-1f57d4s-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var FramerGFiJE27cf = withCSS2(Component2, css4, "framer-kjRJ3");
var stdin_default3 = FramerGFiJE27cf;
FramerGFiJE27cf.displayName = "FAQ section";
FramerGFiJE27cf.defaultProps = {
	height: 462,
	width: 720,
};
addFonts2(
	FramerGFiJE27cf,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LayoutJumpPreventerFonts,
		...FAQAccordionFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/SzUNN0kHl2QaxGOitf7Z/ZfLCjLVJd8d9naXQ8ZT9/lOqyWx384.js
var SeperatorFonts = getFonts2(stdin_default);
var FAQSectionFonts = getFonts2(stdin_default3);
var SmartComponentScopedContainerWithFX = withFX(
	SmartComponentScopedContainer2,
);
var serializationHash3 = "framer-9xpMn";
var variantClassNames3 = {
	ntBUFNamL: "framer-v-1fet5e4",
};
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 60,
	delay: 0.4,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef4(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		defaultVariant: "ntBUFNamL",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.section
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-1fet5e4",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"ntBUFNamL"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion3.div
							className={"framer-17794xm"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"DaaPlcv8a"}
						>
							<ComponentViewportProvider2
								height={207}
								width={`calc(min(${componentViewport?.width || "100vw"}, 1200px) - 96px)`}
								y={
									(componentViewport?.y || 0) +
									100 +
									(((componentViewport?.height || 930) - 200 - 731) / 2 +
										0 +
										0) +
									0 +
									0
								}
							>
								<SmartComponentScopedContainer2
									className={"framer-1azd6w9-container"}
									layoutDependency={layoutDependency}
									layoutId={"YsdFdUFDs-container"}
									nodeId={"YsdFdUFDs"}
									rendersWithMotion={true}
									scopeId={"lOqyWx384"}
								>
									{_jsx4(stdin_default, {
										height: "100%",
										id: "YsdFdUFDs",
										layoutId: "YsdFdUFDs",
										LZ8_yaAGB: "Common questions with Clear answers",
										style: {
											width: "100%",
										},
										sWnc4R5C9:
											"Here are answers to the most common things people ask before getting started.",
										variant: "GCevxSqGm",
										width: "100%",
										ZBMvVPx0w: "FAQ's",
									})}
								</SmartComponentScopedContainer2>
							</ComponentViewportProvider2>
							<ComponentViewportProvider2
								height={468}
								width={`min(min(${componentViewport?.width || "100vw"}, 1200px) - 96px, 800px)`}
								y={
									(componentViewport?.y || 0) +
									100 +
									(((componentViewport?.height || 930) - 200 - 731) / 2 +
										0 +
										0) +
									0 +
									263
								}
							>
								<SmartComponentScopedContainerWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1nonk7c-container"}
									layoutDependency={layoutDependency}
									layoutId={"dW48JpFBk-container"}
									nodeId={"dW48JpFBk"}
									rendersWithMotion={true}
									scopeId={"lOqyWx384"}
								>
									{_jsx4(stdin_default3, {
										height: "100%",
										id: "dW48JpFBk",
										layoutId: "dW48JpFBk",
										style: {
											maxWidth: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainerWithFX>
							</ComponentViewportProvider2>
						</motion3.div>
					</motion3.section>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-9xpMn.framer-1c2x5n2, .framer-9xpMn .framer-1c2x5n2 { display: block; }",
	".framer-9xpMn.framer-1fet5e4 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 0px 100px 0px; position: relative; width: 1200px; }",
	".framer-9xpMn .framer-17794xm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px 48px 0px 48px; position: relative; width: 100%; }",
	".framer-9xpMn .framer-1azd6w9-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-9xpMn .framer-1nonk7c-container { flex: none; height: auto; max-width: 800px; position: relative; width: 100%; }",
];
var FramerlOqyWx384 = withCSS3(Component3, css5, "framer-9xpMn");
var stdin_default4 = FramerlOqyWx384;
FramerlOqyWx384.displayName = "FAQ";
FramerlOqyWx384.defaultProps = {
	height: 930,
	width: 1200,
};
addFonts3(
	FramerlOqyWx384,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...SeperatorFonts,
		...FAQSectionFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var faq_default = ComponentWithRoot;
export { faq_default as default };
