// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ac4b2f1e7a67ec54 "Alytics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 3' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PUETUJTD.js";
import { stdin_default } from "./chunks/chunk-KYLAGT6A.js";
import "./chunks/chunk-XAKJVEAV.js";
import "./chunks/chunk-JCMURR45.js";
import { className, css, fonts } from "./chunks/chunk-T7ZDJKBY.js";
import { routes } from "./chunks/chunk-D3NEX6SN.js";

// virtual:features
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/TjK2IML6T3lDaIx6if5h/EaIZeNA3Myqkd8E7xd7Y/vQWEkFckh.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/q5reFkekRLO19Xqbmlgb/WCiL84dSeexaaUJfXyHk/we0xFLG5H.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["ROBSscKVu", "PgZmH1Khd", "oKTuKwv2y"];
var serializationHash = "framer-xf2b1";
var variantClassNames = {
	oKTuKwv2y: "framer-v-19up9go",
	PgZmH1Khd: "framer-v-n3scy8",
	ROBSscKVu: "framer-v-2bav7t",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "ROBSscKVu",
	Mobile: "oKTuKwv2y",
	Tab: "PgZmH1Khd",
};
var getProps = ({ description, height, id, image, title, width, ...props }) => {
	return {
		...props,
		BStHGxTMw: image ?? props.BStHGxTMw,
		J7BwqYAls: title ?? props.J7BwqYAls ?? "title",
		JFx6MNRJH: description ?? props.JFx6MNRJH ?? "Description",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ROBSscKVu",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		J7BwqYAls,
		JFx6MNRJH,
		BStHGxTMw,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ROBSscKVu",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-2bav7t",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"ROBSscKVu"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							boxShadow: "0px 1px 20px 0px rgba(0, 0, 0, 0.03)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								oKTuKwv2y: {
									"data-framer-name": "Mobile",
								},
								PgZmH1Khd: {
									"data-framer-name": "Tab",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-j29pnv"}
							data-border={true}
							data-framer-name={"Image container"}
							layoutDependency={layoutDependency}
							layoutId={"kFB7mcZtJ"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-a0d7c77d-bb42-477c-affc-b56f45ae9a8a, rgb(235, 235, 235))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
							variants={{
								oKTuKwv2y: {
									borderBottomLeftRadius: 12,
									borderBottomRightRadius: 12,
									borderTopLeftRadius: 12,
									borderTopRightRadius: 12,
								},
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 16 + 0 + 0,
									),
									sizes: `calc(${componentViewport?.width || "100vw"} - 32px)`,
									...toResponsiveImage(BStHGxTMw),
								}}
								className={"framer-11rxytx"}
								layoutDependency={layoutDependency}
								layoutId={"VHIOGNBz6"}
								{...addPropertyOverrides(
									{
										oKTuKwv2y: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 10 + 0 + 0,
												),
												sizes: `calc(${componentViewport?.width || "100vw"} - 20px)`,
												...toResponsiveImage(BStHGxTMw),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
						<motion.div
							className={"framer-56qeuq"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"gHiaMI54K"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1xhp915"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"xAK12N6Br"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={J7BwqYAls}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-nrofro"}
										data-styles-preset={"egFybnJEl"}
									>
										{"title"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-b84ysj"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"oUmLCeVXi"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={JFx6MNRJH}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-oo9bt8"}
										data-styles-preset={"Qd8jNwk_8"}
									>
										{"Description"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xf2b1.framer-8l8tu6, .framer-xf2b1 .framer-8l8tu6 { display: block; }",
	".framer-xf2b1.framer-2bav7t { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px 16px 24px 16px; position: relative; width: 500px; }",
	".framer-xf2b1 .framer-j29pnv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 280px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-xf2b1 .framer-11rxytx { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-xf2b1 .framer-56qeuq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 8px 0px 8px; position: relative; width: 100%; }",
	".framer-xf2b1 .framer-1xhp915 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-xf2b1 .framer-b84ysj { flex: none; height: auto; max-width: 400px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-xf2b1.framer-v-n3scy8.framer-2bav7t { width: 400px; }",
	".framer-xf2b1.framer-v-n3scy8 .framer-j29pnv { height: 250px; }",
	".framer-xf2b1.framer-v-19up9go.framer-2bav7t { gap: 16px; padding: 10px 10px 24px 10px; width: 300px; }",
	".framer-xf2b1.framer-v-19up9go .framer-j29pnv { height: 200px; }",
	".framer-xf2b1.framer-v-19up9go .framer-11rxytx { bottom: -80px; }",
	...css2,
	...css,
	'.framer-xf2b1[data-border="true"]::after, .framer-xf2b1 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerwe0xFLG5H = withCSS(Component, css3, "framer-xf2b1");
var stdin_default2 = Framerwe0xFLG5H;
Framerwe0xFLG5H.displayName = "Features card";
Framerwe0xFLG5H.defaultProps = {
	height: 392,
	width: 500,
};
addPropertyControls(Framerwe0xFLG5H, {
	variant: {
		options: ["ROBSscKVu", "PgZmH1Khd", "oKTuKwv2y"],
		optionTitles: ["Desktop", "Tab", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	J7BwqYAls: {
		defaultValue: "title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	JFx6MNRJH: {
		defaultValue: "Description",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	BStHGxTMw: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	Framerwe0xFLG5H,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/TjK2IML6T3lDaIx6if5h/EaIZeNA3Myqkd8E7xd7Y/vQWEkFckh.js
var SeperatorFonts = getFonts(stdin_default);
var FeaturesCardFonts = getFonts(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder2 = ["dcyOO2PSB", "R58oq2Nru"];
var serializationHash2 = "framer-Y4gIg";
var variantClassNames2 = {
	dcyOO2PSB: "framer-v-1nptw25",
	R58oq2Nru: "framer-v-e5hup8",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 80,
};
var transition2 = {
	damping: 60,
	delay: 0.2,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var transition3 = {
	damping: 60,
	delay: 0.4,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Variant 1": "dcyOO2PSB",
	"Variant 3": "R58oq2Nru",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "dcyOO2PSB",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "dcyOO2PSB",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1nptw25",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"dcyOO2PSB"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								R58oq2Nru: {
									"data-framer-name": "Variant 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1708il2"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"REgYRau9T"}
						>
							<ComponentViewportProvider
								height={207}
								width={`calc(min(${componentViewport?.width || "100vw"}, 1200px) - 96px)`}
								y={
									(componentViewport?.y || 0) +
									100 +
									(((componentViewport?.height || 1288) - 200 - 1067) / 2 +
										0 +
										0) +
									0 +
									0
								}
								{...addPropertyOverrides2(
									{
										R58oq2Nru: {
											width: "288px",
											y:
												(componentViewport?.y || 0) +
												35 +
												(((componentViewport?.height || 2305) - 70 - 2235) / 2 +
													0 +
													0) +
												0 +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-o0okn0-container"}
									layoutDependency={layoutDependency}
									layoutId={"VWM8NBagw-container"}
									nodeId={"VWM8NBagw"}
									rendersWithMotion={true}
									scopeId={"vQWEkFckh"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "VWM8NBagw",
										layoutId: "VWM8NBagw",
										LZ8_yaAGB: "Make your platform work harder for you",
										style: {
											width: "100%",
										},
										sWnc4R5C9:
											"Streamline your business with unified metrics and AI-powered analytics\u2014all in one place.",
										variant: "GCevxSqGm",
										width: "100%",
										ZBMvVPx0w: "Unique Features",
										...addPropertyOverrides2(
											{
												R58oq2Nru: {
													AHR9OFUPD: void 0,
													variant: "YYiQUhkak",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion2.div
								className={"framer-9swxzr"}
								data-framer-name={"Cards"}
								layoutDependency={layoutDependency}
								layoutId={"v1FTXa0wM"}
							>
								<motion2.div
									className={"framer-daiywt"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"wNLnrsRDo"}
								>
									<ComponentViewportProvider
										height={392}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 116px) / 2, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 1288) - 200 - 1067) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides2(
											{
												R58oq2Nru: {
													width: "288px",
													y:
														(componentViewport?.y || 0) +
														35 +
														(((componentViewport?.height || 2305) - 70 - 2235) /
															2 +
															0 +
															0) +
														0 +
														263 +
														0 +
														0 +
														0 +
														98,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1atjf7v-container"}
											layoutDependency={layoutDependency}
											layoutId={"ZHLyBKRq_-container"}
											nodeId={"ZHLyBKRq_"}
											rendersWithMotion={true}
											scopeId={"vQWEkFckh"}
										>
											{_jsx2(stdin_default2, {
												BStHGxTMw: addImageAlt(
													{
														pixelHeight: 1080,
														pixelWidth: 1920,
														src: "https://framerusercontent.com/images/Z1jXBbyRKY2gKHAfYKLGRcgNJUs.png?width=1920&height=1080",
														srcSet:
															"https://framerusercontent.com/images/Z1jXBbyRKY2gKHAfYKLGRcgNJUs.png?scale-down-to=512&width=1920&height=1080 512w,https://framerusercontent.com/images/Z1jXBbyRKY2gKHAfYKLGRcgNJUs.png?scale-down-to=1024&width=1920&height=1080 1024w,https://framerusercontent.com/images/Z1jXBbyRKY2gKHAfYKLGRcgNJUs.png?width=1920&height=1080 1920w",
													},
													"Dashboard showing MRR of $69,897 and 1206 active users with an upward trend graph.",
												),
												height: "100%",
												id: "ZHLyBKRq_",
												J7BwqYAls: "AI Calling Agents ",
												JFx6MNRJH:
													"24/7 call handling, lead qualification, and appointment booking. Boost conversions by over 85%.",
												layoutId: "ZHLyBKRq_",
												style: {
													width: "100%",
												},
												variant: "ROBSscKVu",
												width: "100%",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={392}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 116px) / 2, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 1288) - 200 - 1067) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides2(
											{
												R58oq2Nru: {
													width: "288px",
													y:
														(componentViewport?.y || 0) +
														35 +
														(((componentViewport?.height || 2305) - 70 - 2235) /
															2 +
															0 +
															0) +
														0 +
														263 +
														0 +
														0 +
														0 +
														510,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1ngi04l-container"}
											layoutDependency={layoutDependency}
											layoutId={"V2y2vAJqA-container"}
											nodeId={"V2y2vAJqA"}
											rendersWithMotion={true}
											scopeId={"vQWEkFckh"}
										>
											{_jsx2(stdin_default2, {
												BStHGxTMw: addImageAlt(
													{
														pixelHeight: 2216,
														pixelWidth: 4e3,
														src: "https://framerusercontent.com/images/eUVqpWJ3R7uJaOJnHDYhRMM4WPE.png?width=4000&height=2216",
														srcSet:
															"https://framerusercontent.com/images/eUVqpWJ3R7uJaOJnHDYhRMM4WPE.png?scale-down-to=512&width=4000&height=2216 512w,https://framerusercontent.com/images/eUVqpWJ3R7uJaOJnHDYhRMM4WPE.png?scale-down-to=1024&width=4000&height=2216 1024w,https://framerusercontent.com/images/eUVqpWJ3R7uJaOJnHDYhRMM4WPE.png?scale-down-to=2048&width=4000&height=2216 2048w,https://framerusercontent.com/images/eUVqpWJ3R7uJaOJnHDYhRMM4WPE.png?width=4000&height=2216 4000w",
													},
													'AI suggesting actions like "Optimize onboarding flow" and "Raise pricing tier" based on user data.',
												),
												height: "100%",
												id: "V2y2vAJqA",
												J7BwqYAls: "AI Growth Insights",
												JFx6MNRJH:
													"Actionable suggestions from your data, without digging into spreadsheets or dashboards.",
												layoutId: "V2y2vAJqA",
												style: {
													width: "100%",
												},
												variant: "ROBSscKVu",
												width: "100%",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
								</motion2.div>
								<motion2.div
									className={"framer-1hu7y9k"}
									data-framer-name={"Bottom"}
									layoutDependency={layoutDependency}
									layoutId={"vfAtsYoj0"}
								>
									<ComponentViewportProvider
										height={392}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 116px) / 2, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 1288) - 200 - 1067) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											412 +
											0
										}
										{...addPropertyOverrides2(
											{
												R58oq2Nru: {
													width: "288px",
													y:
														(componentViewport?.y || 0) +
														35 +
														(((componentViewport?.height || 2305) - 70 - 2235) /
															2 +
															0 +
															0) +
														0 +
														263 +
														0 +
														1020 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-44ikw3-container"}
											layoutDependency={layoutDependency}
											layoutId={"EyaWufN1t-container"}
											nodeId={"EyaWufN1t"}
											rendersWithMotion={true}
											scopeId={"vQWEkFckh"}
										>
											{_jsx2(stdin_default2, {
												BStHGxTMw: addImageAlt(
													{
														pixelHeight: 1080,
														pixelWidth: 1920,
														src: "https://framerusercontent.com/images/1B9HqvduOMtbO2GXvmuAfrB6I.png?width=1920&height=1080",
														srcSet:
															"https://framerusercontent.com/images/1B9HqvduOMtbO2GXvmuAfrB6I.png?scale-down-to=512&width=1920&height=1080 512w,https://framerusercontent.com/images/1B9HqvduOMtbO2GXvmuAfrB6I.png?scale-down-to=1024&width=1920&height=1080 1024w,https://framerusercontent.com/images/1B9HqvduOMtbO2GXvmuAfrB6I.png?width=1920&height=1080 1920w",
													},
													"Integration performance stats for Nuvio, Klyra, and Veltix with percentage changes.",
												),
												height: "100%",
												id: "EyaWufN1t",
												J7BwqYAls: "All-in-One Marketing CRM",
												JFx6MNRJH:
													"Centralize your entire pipeline to shorten sales cycles by up to 40%.",
												layoutId: "EyaWufN1t",
												style: {
													width: "100%",
												},
												variant: "ROBSscKVu",
												width: "100%",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={392}
										width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 116px) / 2, 1px)`}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 1288) - 200 - 1067) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											412 +
											0
										}
										{...addPropertyOverrides2(
											{
												R58oq2Nru: {
													width: "288px",
													y:
														(componentViewport?.y || 0) +
														35 +
														(((componentViewport?.height || 2305) - 70 - 2235) /
															2 +
															0 +
															0) +
														0 +
														263 +
														0 +
														1020 +
														0 +
														412,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-r55vco-container"}
											layoutDependency={layoutDependency}
											layoutId={"G7IdCKZiU-container"}
											nodeId={"G7IdCKZiU"}
											rendersWithMotion={true}
											scopeId={"vQWEkFckh"}
										>
											{_jsx2(stdin_default2, {
												BStHGxTMw: addImageAlt(
													{
														pixelHeight: 3325,
														pixelWidth: 6e3,
														src: "https://framerusercontent.com/images/ukxSF4evyjJNRAA1AxD2RgCC4ds.png?width=6000&height=3325",
														srcSet:
															"https://framerusercontent.com/images/ukxSF4evyjJNRAA1AxD2RgCC4ds.png?scale-down-to=512&width=6000&height=3325 512w,https://framerusercontent.com/images/ukxSF4evyjJNRAA1AxD2RgCC4ds.png?scale-down-to=1024&width=6000&height=3325 1024w,https://framerusercontent.com/images/ukxSF4evyjJNRAA1AxD2RgCC4ds.png?scale-down-to=2048&width=6000&height=3325 2048w,https://framerusercontent.com/images/ukxSF4evyjJNRAA1AxD2RgCC4ds.png?scale-down-to=4096&width=6000&height=3325 4096w,https://framerusercontent.com/images/ukxSF4evyjJNRAA1AxD2RgCC4ds.png?width=6000&height=3325 6000w",
													},
													"Retention graph with user return notifications for analyzing feature effectiveness.",
												),
												height: "100%",
												id: "G7IdCKZiU",
												J7BwqYAls: "AI Dashboard & Reports",
												JFx6MNRJH:
													"Eliminate manual reporting. Get real-time, actionable insights that help you grow revenue by 20%.",
												layoutId: "G7IdCKZiU",
												style: {
													width: "100%",
												},
												variant: "ROBSscKVu",
												width: "100%",
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
								</motion2.div>
							</motion2.div>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Y4gIg.framer-1b7bh95, .framer-Y4gIg .framer-1b7bh95 { display: block; }",
	".framer-Y4gIg.framer-1nptw25 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 0px 100px 0px; position: relative; width: 1200px; }",
	".framer-Y4gIg .framer-1708il2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px 48px 0px 48px; position: relative; width: 100%; }",
	".framer-Y4gIg .framer-o0okn0-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-Y4gIg .framer-9swxzr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Y4gIg .framer-daiywt, .framer-Y4gIg .framer-1hu7y9k { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Y4gIg .framer-1atjf7v-container, .framer-Y4gIg .framer-1ngi04l-container, .framer-Y4gIg .framer-44ikw3-container, .framer-Y4gIg .framer-r55vco-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-Y4gIg.framer-v-e5hup8.framer-1nptw25 { padding: 35px 0px 35px 0px; width: 390px; }",
	".framer-Y4gIg.framer-v-e5hup8 .framer-1708il2 { height: 2235px; width: 384px; }",
	".framer-Y4gIg.framer-v-e5hup8 .framer-o0okn0-container { order: 0; }",
	".framer-Y4gIg.framer-v-e5hup8 .framer-9swxzr { height: 1824px; order: 1; }",
	".framer-Y4gIg.framer-v-e5hup8 .framer-daiywt { flex: 1 0 0px; flex-direction: column; height: 1px; }",
	".framer-Y4gIg.framer-v-e5hup8 .framer-1atjf7v-container, .framer-Y4gIg.framer-v-e5hup8 .framer-1ngi04l-container, .framer-Y4gIg.framer-v-e5hup8 .framer-44ikw3-container, .framer-Y4gIg.framer-v-e5hup8 .framer-r55vco-container { flex: none; width: 100%; }",
	".framer-Y4gIg.framer-v-e5hup8 .framer-1hu7y9k { flex-direction: column; }",
];
var FramervQWEkFckh = withCSS2(Component2, css4, "framer-Y4gIg");
var stdin_default3 = FramervQWEkFckh;
FramervQWEkFckh.displayName = "Features";
FramervQWEkFckh.defaultProps = {
	height: 1288,
	width: 1200,
};
addPropertyControls2(FramervQWEkFckh, {
	variant: {
		options: ["dcyOO2PSB", "R58oq2Nru"],
		optionTitles: ["Variant 1", "Variant 3"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramervQWEkFckh,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...SeperatorFonts,
		...FeaturesCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:features
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "R58oq2Nru",
	xl: "dcyOO2PSB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeaturesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var features_default = ComponentWithRoot;
export { features_default as default };
