// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ac4b2f1e7a67ec54 "Alytics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tab' | 'Mobile' // Variant
}} Props

 */
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-43AO5CDN.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PUETUJTD.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
	stdin_default,
} from "./chunks/chunk-EH5635TV.js";
import { className, css, fonts } from "./chunks/chunk-T7ZDJKBY.js";
import { routes } from "./chunks/chunk-D3NEX6SN.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8C9fvBPEpYrclVcjaGi9/E0ISTuUmJvoQkS5CUJ0b/X69dVUaYG.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/6lO9STuPxZ9FEnwafxsc/Qr3GyLWHA12h6usSs6aY/eglQVlcv4.js
import { fontStore } from "unframer";
fontStore.loadFonts([]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css5 = [
	".framer-md5Fd .framer-styles-preset-1meb3h0:not(.rich-text-wrapper), .framer-md5Fd .framer-styles-preset-1meb3h0.rich-text-wrapper a { --framer-link-hover-text-color: rgba(87, 87, 87, 0.7); --framer-link-text-color: var(--token-cb2243e7-371d-4dd4-a3f5-00f97c4730ab, #575757); transition-delay: 0s; transition-duration: 0.4s; transition-property: color; transition-timing-function: cubic-bezier(0.44, 0, 0.56, 1); }",
];
var className5 = "framer-md5Fd";

// /:https://framerusercontent.com/modules/8C9fvBPEpYrclVcjaGi9/E0ISTuUmJvoQkS5CUJ0b/X69dVUaYG.js
var ButtonFonts = getFonts(stdin_default);
var cycleOrder = ["w5zdoJ9PP", "L_AHvJ46D", "uDZC0uvO3"];
var serializationHash = "framer-SyXgz";
var variantClassNames = {
	L_AHvJ46D: "framer-v-olv6ne",
	uDZC0uvO3: "framer-v-1hygkis",
	w5zdoJ9PP: "framer-v-rnu210",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "w5zdoJ9PP",
	Mobile: "uDZC0uvO3",
	Tab: "L_AHvJ46D",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "w5zdoJ9PP",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "w5zdoJ9PP",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className2,
		className,
		className4,
		className5,
		className3,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-rnu210",
							className6,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"w5zdoJ9PP"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
							boxShadow: "0px -1px 20px 0px rgba(0, 0, 0, 0.03)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								L_AHvJ46D: {
									"data-framer-name": "Tab",
								},
								uDZC0uvO3: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-tmb415"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"bsLxxp8Dx"}
						>
							<motion.div
								className={"framer-ze1luw"}
								data-framer-name={"Top"}
								layoutDependency={layoutDependency}
								layoutId={"K1JDu6y8U"}
							>
								<motion.div
									className={"framer-1c0ajd3"}
									data-framer-name={"Left container"}
									layoutDependency={layoutDependency}
									layoutId={"WPlKuDUYp"}
								>
									<motion.div
										className={"framer-17i0qno"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"WChAgKdnE"}
									>
										<motion.div
											className={"framer-7qp9kz"}
											data-framer-name={"Logo container"}
											layoutDependency={layoutDependency}
											layoutId={"hWbFRYhE9"}
										>
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 1188.8,
													intrinsicWidth: 2257.6,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															48 +
															(((componentViewport?.height || 312) -
																68 -
																261.4) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0,
													),
													pixelHeight: 1486,
													pixelWidth: 2822,
													sizes: "54px",
													src: "https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486",
													srcSet:
														"https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=512&width=2822&height=1486 512w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=1024&width=2822&height=1486 1024w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=2048&width=2822&height=1486 2048w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486 2822w",
												}}
												className={"framer-1vq24pu"}
												data-framer-name={"AI2MARKETLOGO"}
												layoutDependency={layoutDependency}
												layoutId={"tqRCupl13"}
												{...addPropertyOverrides(
													{
														L_AHvJ46D: {
															background: {
																alt: "",
																fit: "fill",
																intrinsicHeight: 1188.8,
																intrinsicWidth: 2257.6,
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		48 +
																		(((componentViewport?.height || 308) -
																			68 -
																			261.4) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0,
																),
																pixelHeight: 1486,
																pixelWidth: 2822,
																sizes: "54px",
																src: "https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486",
																srcSet:
																	"https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=512&width=2822&height=1486 512w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=1024&width=2822&height=1486 1024w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=2048&width=2822&height=1486 2048w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486 2822w",
															},
														},
														uDZC0uvO3: {
															background: {
																alt: "",
																fit: "fill",
																intrinsicHeight: 1188.8,
																intrinsicWidth: 2257.6,
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		48 +
																		(((componentViewport?.height || 839) -
																			68 -
																			747) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0,
																),
																pixelHeight: 1486,
																pixelWidth: 2822,
																sizes: "54px",
																src: "https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486",
																srcSet:
																	"https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=512&width=2822&height=1486 512w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=1024&width=2822&height=1486 1024w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=2048&width=2822&height=1486 2048w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486 2822w",
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1jhkbsf"}
												data-framer-name={"Name"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"oeXdYeQCH"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h4
														className={"framer-styles-preset-nrofro"}
														data-styles-preset={"egFybnJEl"}
													>
														{"AI2Market"}
													</motion.h4>
												</React.Fragment>
											</RichText>
										</motion.div>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-16pkru5"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"vNMnfcmQc"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-oo9bt8"}
													data-styles-preset={"Qd8jNwk_8"}
												>
													{
														"Turn complex data into clear, actionable insights so you can make smarter decisions and drive growth with confidence"
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<ComponentViewportProvider
										height={42}
										y={
											(componentViewport?.y || 0) +
											48 +
											(((componentViewport?.height || 312) - 68 - 261.4) / 2 +
												0 +
												0) +
											0 +
											0 +
											0 +
											0 +
											157
										}
										{...addPropertyOverrides(
											{
												L_AHvJ46D: {
													y:
														(componentViewport?.y || 0) +
														48 +
														(((componentViewport?.height || 308) - 68 - 261.4) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														157,
												},
												uDZC0uvO3: {
													y:
														(componentViewport?.y || 0) +
														48 +
														(((componentViewport?.height || 839) - 68 - 747) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														157,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1qyl0q5-container"}
											layoutDependency={layoutDependency}
											layoutId={"UeL2_jNNP-container"}
											nodeId={"UeL2_jNNP"}
											rendersWithMotion={true}
											scopeId={"X69dVUaYG"}
										>
											{_jsx(stdin_default, {
												e5w0UxZNt:
													"https://framer.com/remix/sYqnVgaJ6jfdOyaORZkY",
												height: "100%",
												hKzSQEl_0: "Get Free Consultation ",
												id: "UeL2_jNNP",
												layoutId: "UeL2_jNNP",
												VEpndFiaz: true,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-i4c381"}
									data-framer-name={"Links container"}
									layoutDependency={layoutDependency}
									layoutId={"qv9nnFXe1"}
								>
									<motion.div
										className={"framer-1lts0aj"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"KzcWa7hFBTBjyVA4da"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-5o8y67"}
											data-framer-name={"Heading"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"fRO3BspHn"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h5
													className={"framer-styles-preset-ob6p3i"}
													data-styles-preset={"uDzEgMsNq"}
												>
													{"Sections"}
												</motion.h5>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-wcgse6"}
											data-framer-name={"Links"}
											layoutDependency={layoutDependency}
											layoutId={"AjlgIcf7l"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-134t4vb"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"zzJCqGAvR"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={{
																hash: ":dcyOO2PSB",
																webPageId: "SiMIe5pOV",
															}}
															motionChild={true}
															nodeId={"zzJCqGAvR"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={true}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Features"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-23uh7z"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"A37SoJOYm"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={{
																hash: ":Jn3wngbgL",
																webPageId: "SiMIe5pOV",
															}}
															motionChild={true}
															nodeId={"A37SoJOYm"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={true}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Benefits"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-erztd9"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"RtIFWYLzC"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={{
																hash: ":Cuvf1oZ36",
																webPageId: "SiMIe5pOV",
															}}
															motionChild={true}
															nodeId={"RtIFWYLzC"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={true}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Integrations"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1bfitun"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"BYLOD484Y"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={{
																hash: ":rjsy3UbtH",
																webPageId: "SiMIe5pOV",
															}}
															motionChild={true}
															nodeId={"BYLOD484Y"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={true}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Pricing"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1y1l4to"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"rzP_tp0fP"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={{
																hash: ":ntBUFNamL",
																webPageId: "SiMIe5pOV",
															}}
															motionChild={true}
															nodeId={"rzP_tp0fP"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={true}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"FAQ"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-2f81h3"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"x_Ck9KNsd"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-99krjs"}
											data-framer-name={"Heading"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"TBmZTBiq3"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h5
													className={"framer-styles-preset-ob6p3i"}
													data-styles-preset={"uDzEgMsNq"}
												>
													{"Socials"}
												</motion.h5>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-2sep2"}
											data-framer-name={"Links"}
											layoutDependency={layoutDependency}
											layoutId={"oPtLa5GQY"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-150a0lm"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"hSYRtTLqO"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={"https://www.instagram.com/"}
															motionChild={true}
															nodeId={"hSYRtTLqO"}
															openInNewTab={true}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Instagram"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-2f4bn5"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"Je11tnK0M"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={"https://x.com/"}
															motionChild={true}
															nodeId={"Je11tnK0M"}
															openInNewTab={true}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Twitter/X"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-55z3l0"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"j7JXiZNf1"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={"https://www.linkedin.com/"}
															motionChild={true}
															nodeId={"j7JXiZNf1"}
															openInNewTab={true}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Linkedin"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-1mq03sl"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"epgGcC6sK"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1247jok"}
											data-framer-name={"Heading"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"hdXEDh20_"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h5
													className={"framer-styles-preset-ob6p3i"}
													data-styles-preset={"uDzEgMsNq"}
												>
													{"Pages"}
												</motion.h5>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-1kt4qz4"}
											data-framer-name={"Links"}
											layoutDependency={layoutDependency}
											layoutId={"Dqr8W4Kvd"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-ghy29m"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"aisBs2ANc"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={{
																webPageId: "SiMIe5pOV",
															}}
															motionChild={true}
															nodeId={"aisBs2ANc"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={true}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Home"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-zrx9n9"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"snjgXwXMu"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={{
																webPageId: "oZLBf0uQT",
															}}
															motionChild={true}
															nodeId={"snjgXwXMu"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"Newsletter"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1tkctd0"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"WLixYAUbK"}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
													>
														<Link
															href={{
																webPageId: "VxPcDsyke",
															}}
															motionChild={true}
															nodeId={"WLixYAUbK"}
															openInNewTab={false}
															relValues={[]}
															scopeId={"X69dVUaYG"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1meb3h0"}
																data-styles-preset={"eglQVlcv4"}
															>
																{"404"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-1kviont"}
								data-border={true}
								data-framer-name={"Bottom"}
								layoutDependency={layoutDependency}
								layoutId={"aoJLff6YO"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color":
										"var(--token-a0d7c77d-bb42-477c-affc-b56f45ae9a8a, rgb(235, 235, 235))",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "1px",
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-7blpl0"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ei1CtO20Z"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e1ef367e-e23b-4a9e-826b-77a848c7f0b3, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-11otiv6"}
											data-styles-preset={"Nsh0fVFRK"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e1ef367e-e23b-4a9e-826b-77a848c7f0b3, rgb(0, 0, 0)))",
											}}
										>
											{"All Rights Reserved \xA9 2024 AI2Market"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<Link
									href={"https://x.com/axadkhaleel"}
									motionChild={true}
									nodeId={"uteVnAES4"}
									openInNewTab={true}
									scopeId={"X69dVUaYG"}
								>
									<motion.a
										className={"framer-692lf9 framer-1ii8b36"}
										data-framer-name={"Me"}
										layoutDependency={layoutDependency}
										layoutId={"uteVnAES4"}
									/>
								</Link>
							</motion.div>
						</motion.div>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SyXgz.framer-1ii8b36, .framer-SyXgz .framer-1ii8b36 { display: block; }",
	".framer-SyXgz.framer-rnu210 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 48px 48px 20px 48px; position: relative; width: 1200px; }",
	".framer-SyXgz .framer-tmb415 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; max-width: 1104px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-SyXgz .framer-ze1luw { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-SyXgz .framer-1c0ajd3 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-SyXgz .framer-17i0qno { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-SyXgz .framer-7qp9kz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-SyXgz .framer-1vq24pu { aspect-ratio: 1.899057873485868 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 29px); overflow: visible; position: relative; width: 54px; }",
	".framer-SyXgz .framer-1jhkbsf, .framer-SyXgz .framer-134t4vb, .framer-SyXgz .framer-23uh7z, .framer-SyXgz .framer-erztd9, .framer-SyXgz .framer-1bfitun, .framer-SyXgz .framer-1y1l4to, .framer-SyXgz .framer-150a0lm, .framer-SyXgz .framer-2f4bn5, .framer-SyXgz .framer-55z3l0, .framer-SyXgz .framer-ghy29m, .framer-SyXgz .framer-zrx9n9, .framer-SyXgz .framer-1tkctd0, .framer-SyXgz .framer-7blpl0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-SyXgz .framer-16pkru5 { flex: none; height: auto; max-width: 300px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-SyXgz .framer-1qyl0q5-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-SyXgz .framer-i4c381 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; max-width: 500px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-SyXgz .framer-1lts0aj, .framer-SyXgz .framer-2f81h3, .framer-SyXgz .framer-1mq03sl { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-SyXgz .framer-5o8y67, .framer-SyXgz .framer-99krjs, .framer-SyXgz .framer-1247jok { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-SyXgz .framer-wcgse6, .framer-SyXgz .framer-2sep2, .framer-SyXgz .framer-1kt4qz4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-SyXgz .framer-1kviont { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 20px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-SyXgz .framer-692lf9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 22px; min-width: 181px; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-SyXgz.framer-v-olv6ne.framer-rnu210 { padding: 48px 32px 20px 32px; width: 810px; }",
	".framer-SyXgz.framer-v-olv6ne .framer-tmb415 { max-width: 748px; }",
	".framer-SyXgz.framer-v-olv6ne .framer-1lts0aj, .framer-SyXgz.framer-v-olv6ne .framer-2f81h3, .framer-SyXgz.framer-v-olv6ne .framer-1mq03sl { gap: 12px; }",
	".framer-SyXgz.framer-v-1hygkis.framer-rnu210 { padding: 48px 16px 20px 16px; width: 390px; }",
	".framer-SyXgz.framer-v-1hygkis .framer-tmb415 { max-width: 348px; }",
	".framer-SyXgz.framer-v-1hygkis .framer-ze1luw { flex-direction: column; gap: 20px; justify-content: flex-start; }",
	".framer-SyXgz.framer-v-1hygkis .framer-1c0ajd3 { flex: none; width: 100%; }",
	".framer-SyXgz.framer-v-1hygkis .framer-i4c381 { flex: none; flex-direction: column; width: 100%; }",
	".framer-SyXgz.framer-v-1hygkis .framer-1lts0aj, .framer-SyXgz.framer-v-1hygkis .framer-2f81h3, .framer-SyXgz.framer-v-1hygkis .framer-1mq03sl { flex: none; gap: 12px; width: 100%; }",
	".framer-SyXgz.framer-v-1hygkis .framer-1kviont { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 10px; justify-content: flex-start; }",
	".framer-SyXgz.framer-v-1hygkis .framer-692lf9 { min-height: 23px; }",
	...css2,
	...css,
	...css4,
	...css5,
	...css3,
	'.framer-SyXgz[data-border="true"]::after, .framer-SyXgz [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerX69dVUaYG = withCSS(Component, css6, "framer-SyXgz");
var stdin_default2 = FramerX69dVUaYG;
FramerX69dVUaYG.displayName = "Footer";
FramerX69dVUaYG.defaultProps = {
	height: 312,
	width: 1200,
};
addPropertyControls(FramerX69dVUaYG, {
	variant: {
		options: ["w5zdoJ9PP", "L_AHvJ46D", "uDZC0uvO3"],
		optionTitles: ["Desktop", "Tab", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerX69dVUaYG,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "uDZC0uvO3",
	md: "L_AHvJ46D",
	xl: "w5zdoJ9PP",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
