// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ac4b2f1e7a67ec54 "Alytics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * text?: string // Text
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PUETUJTD.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-EH5635TV.js";
import { stdin_default } from "./chunks/chunk-KYLAGT6A.js";
import "./chunks/chunk-XAKJVEAV.js";
import "./chunks/chunk-JCMURR45.js";
import { className, css, fonts } from "./chunks/chunk-T7ZDJKBY.js";
import { routes } from "./chunks/chunk-D3NEX6SN.js";

// virtual:how-it-works
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Uts7xVvA4U9dixDrlltC/lSNmfgmxbaVEW7wC0KTk/VsPxQDi0B.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/pYKIFL6B29ofOlA57q6M/SCbNGV2NcSApPvKmR3tc/G2vd11hMm.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-opuNU";
var variantClassNames = {
	XHBfIbdoK: "framer-v-1rac43p",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ description, height, id, image, title, width, ...props }) => {
	return {
		...props,
		nHv9AZDwv: title ?? props.nHv9AZDwv ?? "Connect your product",
		Qmh6a_4RQ:
			description ??
			props.Qmh6a_4RQ ??
			"Integrate in minutes with your existing stack\u2014no engineering lift required.",
		Y3xZTreNR: image ?? props.Y3xZTreNR,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		nHv9AZDwv,
		Qmh6a_4RQ,
		Y3xZTreNR,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "XHBfIbdoK",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1rac43p",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"XHBfIbdoK"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							boxShadow: "0px 1px 20px 0px rgba(0, 0, 0, 0.03)",
							...style,
						}}
					>
						<motion.div
							className={"framer-1iungtb"}
							data-framer-name={"Top"}
							layoutDependency={layoutDependency}
							layoutId={"TE5ZSMgiB"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1aed135"}
								data-framer-name={"Heading"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"vOn5rG2Py"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={nHv9AZDwv}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-nrofro"}
										data-styles-preset={"egFybnJEl"}
									>
										{"Connect your product"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-o57fr6"}
								data-framer-name={"Description"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"jzYPVrl_5"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={Qmh6a_4RQ}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-oo9bt8"}
										data-styles-preset={"Qd8jNwk_8"}
									>
										{
											"Integrate in minutes with your existing stack\u2014no engineering lift required."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-xixed9"}
							data-framer-name={"Image container"}
							layoutDependency={layoutDependency}
							layoutId={"g8Xp6EhuW"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 336) - 0 - 402.8) / 2 +
												174.8 +
												0) +
											0,
									),
									sizes: componentViewport?.width || "100vw",
									...toResponsiveImage(Y3xZTreNR),
								}}
								className={"framer-mqvqzu"}
								layoutDependency={layoutDependency}
								layoutId={"eN0IheK70"}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-opuNU.framer-1ulmqrl, .framer-opuNU .framer-1ulmqrl { display: block; }",
	".framer-opuNU.framer-1rac43p { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 352px; will-change: var(--framer-will-change-override, transform); }",
	".framer-opuNU .framer-1iungtb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 20px 20px 10px 20px; position: relative; width: 100%; }",
	".framer-opuNU .framer-1aed135, .framer-opuNU .framer-o57fr6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-opuNU .framer-xixed9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 228px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-opuNU .framer-mqvqzu { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	...css2,
	...css,
];
var FramerG2vd11hMm = withCSS(Component, css3, "framer-opuNU");
var stdin_default3 = FramerG2vd11hMm;
FramerG2vd11hMm.displayName = "How it works";
FramerG2vd11hMm.defaultProps = {
	height: 336,
	width: 352,
};
addPropertyControls(FramerG2vd11hMm, {
	nHv9AZDwv: {
		defaultValue: "Connect your product",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	Qmh6a_4RQ: {
		defaultValue:
			"Integrate in minutes with your existing stack\u2014no engineering lift required.",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	Y3xZTreNR: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerG2vd11hMm,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/Uts7xVvA4U9dixDrlltC/lSNmfgmxbaVEW7wC0KTk/VsPxQDi0B.js
var SeperatorFonts = getFonts(stdin_default);
var ButtonFonts = getFonts(stdin_default2);
var HowItWorksFonts = getFonts(stdin_default3);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder = ["LhC4b14kZ", "J3vv7CwRw"];
var serializationHash2 = "framer-u9Jop";
var variantClassNames2 = {
	J3vv7CwRw: "framer-v-1mxeaak",
	LhC4b14kZ: "framer-v-1ijbfk9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 60,
	delay: 0.2,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var transition3 = {
	damping: 60,
	delay: 0.4,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition4 = {
	damping: 60,
	delay: 0.6,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "LhC4b14kZ",
	"Variant 2": "J3vv7CwRw",
};
var getProps2 = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "LhC4b14kZ",
		vVTdAHXlT:
			text ??
			props.vVTdAHXlT ??
			"From data to clarity\u2014uncover insights, take action, and grow smarter in three simple steps.",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		vVTdAHXlT,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "LhC4b14kZ",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "J3vv7CwRw") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "J3vv7CwRw") return false;
		return true;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1ijbfk9",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"LhC4b14kZ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								J3vv7CwRw: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion2.div
								className={"framer-r24pfz"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"XIcFoib_v"}
							>
								<ComponentViewportProvider
									height={207}
									{...addPropertyOverrides(
										{
											J3vv7CwRw: {
												width: "294px",
												y:
													(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 886) -
														200 -
														(Math.max(
															0,
															((componentViewport?.height || 886) - 200 - 0) /
																1,
														) *
															1 +
															0)) /
														2 +
														0 +
														0) +
													39 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-rlg4ba-container"}
										layoutDependency={layoutDependency}
										layoutId={"sbM_YWOi6-container"}
										nodeId={"sbM_YWOi6"}
										rendersWithMotion={true}
										scopeId={"VsPxQDi0B"}
									>
										{_jsx2(stdin_default, {
											height: "100%",
											id: "sbM_YWOi6",
											layoutId: "sbM_YWOi6",
											LZ8_yaAGB: "Get clear answers in 3 simple steps",
											style: {
												width: "100%",
											},
											sWnc4R5C9: vVTdAHXlT,
											variant: "YYiQUhkak",
											width: "100%",
											ZBMvVPx0w: "How It Works",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion2.div
									className={"framer-lf1le0"}
									data-framer-name={"Cards"}
									layoutDependency={layoutDependency}
									layoutId={"h0O7_V2qJ"}
								>
									<ComponentViewportProvider
										height={42}
										{...addPropertyOverrides(
											{
												J3vv7CwRw: {
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 886) -
															200 -
															(Math.max(
																0,
																((componentViewport?.height || 886) - 200 - 0) /
																	1,
															) *
																1 +
																0)) /
															2 +
															0 +
															0) +
														39 +
														250 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-izbof6-container"}
											layoutDependency={layoutDependency}
											layoutId={"gYlVU2L_w-container"}
											nodeId={"gYlVU2L_w"}
											rendersWithMotion={true}
											scopeId={"VsPxQDi0B"}
										>
											{_jsx2(stdin_default2, {
												e5w0UxZNt:
													"https://framer.com/remix/sYqnVgaJ6jfdOyaORZkY",
												height: "100%",
												hKzSQEl_0: "Claim Free AI Call",
												id: "gYlVU2L_w",
												layoutId: "gYlVU2L_w",
												VEpndFiaz: true,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<motion2.div
										className={"framer-kjtfav"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"OrG7KsdwM"}
									>
										<ComponentViewportProvider
											height={336}
											width={"300px"}
											{...addPropertyOverrides(
												{
													J3vv7CwRw: {
														y:
															(componentViewport?.y || 0) +
															100 +
															(((componentViewport?.height || 886) -
																200 -
																(Math.max(
																	0,
																	((componentViewport?.height || 886) -
																		200 -
																		0) /
																		1,
																) *
																	1 +
																	0)) /
																2 +
																0 +
																0) +
															39 +
															250 +
															0 +
															66 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__framer__animate={{
													transition: transition2,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0.5}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-1uh8ceh-container"}
												layoutDependency={layoutDependency}
												layoutId={"FXDNq1Vb7-container"}
												nodeId={"FXDNq1Vb7"}
												rendersWithMotion={true}
												scopeId={"VsPxQDi0B"}
											>
												{_jsx2(stdin_default3, {
													height: "100%",
													id: "FXDNq1Vb7",
													layoutId: "FXDNq1Vb7",
													nHv9AZDwv: "Book a Free Strategy Call",
													Qmh6a_4RQ:
														"Tell us about your goals. We\u2019ll show you how AI can get you there faster.",
													style: {
														width: "100%",
													},
													width: "100%",
													Y3xZTreNR: addImageAlt(
														{
															pixelHeight: 1080,
															pixelWidth: 1080,
															src: "https://framerusercontent.com/images/Do62WUItr7MQr0OG0a3kR6XhS0.png?width=1080&height=1080",
															srcSet:
																"https://framerusercontent.com/images/Do62WUItr7MQr0OG0a3kR6XhS0.png?scale-down-to=512&width=1080&height=1080 512w,https://framerusercontent.com/images/Do62WUItr7MQr0OG0a3kR6XhS0.png?scale-down-to=1024&width=1080&height=1080 1024w,https://framerusercontent.com/images/Do62WUItr7MQr0OG0a3kR6XhS0.png?width=1080&height=1080 1080w",
														},
														"Logos of tools outward, illustrating easy integration with no engineering required.",
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={336}
											width={"300px"}
											{...addPropertyOverrides(
												{
													J3vv7CwRw: {
														y:
															(componentViewport?.y || 0) +
															100 +
															(((componentViewport?.height || 886) -
																200 -
																(Math.max(
																	0,
																	((componentViewport?.height || 886) -
																		200 -
																		0) /
																		1,
																) *
																	1 +
																	0)) /
																2 +
																0 +
																0) +
															39 +
															250 +
															0 +
															66 +
															0 +
															356,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__framer__animate={{
													transition: transition3,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0.5}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-yvz6jw-container"}
												layoutDependency={layoutDependency}
												layoutId={"MtB_odfkm-container"}
												nodeId={"MtB_odfkm"}
												rendersWithMotion={true}
												scopeId={"VsPxQDi0B"}
											>
												{_jsx2(stdin_default3, {
													height: "100%",
													id: "MtB_odfkm",
													layoutId: "MtB_odfkm",
													nHv9AZDwv: "AI-Powered Growth Plan",
													Qmh6a_4RQ:
														"We build a custom roadmap using data, automation, and personalization tools tailored to your business.",
													style: {
														width: "100%",
													},
													width: "100%",
													Y3xZTreNR: addImageAlt(
														{
															pixelHeight: 3528,
															pixelWidth: 6e3,
															src: "https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?width=6000&height=3528",
															srcSet:
																"https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?scale-down-to=512&width=6000&height=3528 512w,https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?scale-down-to=1024&width=6000&height=3528 1024w,https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?scale-down-to=2048&width=6000&height=3528 2048w,https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?scale-down-to=4096&width=6000&height=3528 4096w,https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?width=6000&height=3528 6000w",
														},
														"Gauge showing levels of user engagement, with tags for high and low engagement percentages.",
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={336}
											width={"300px"}
											{...addPropertyOverrides(
												{
													J3vv7CwRw: {
														y:
															(componentViewport?.y || 0) +
															100 +
															(((componentViewport?.height || 886) -
																200 -
																(Math.max(
																	0,
																	((componentViewport?.height || 886) -
																		200 -
																		0) /
																		1,
																) *
																	1 +
																	0)) /
																2 +
																0 +
																0) +
															39 +
															250 +
															0 +
															66 +
															0 +
															712,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFX
												__framer__animate={{
													transition: transition4,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0.5}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-1n40rvw-container"}
												layoutDependency={layoutDependency}
												layoutId={"tNpYKsbub-container"}
												nodeId={"tNpYKsbub"}
												rendersWithMotion={true}
												scopeId={"VsPxQDi0B"}
											>
												{_jsx2(stdin_default3, {
													height: "100%",
													id: "tNpYKsbub",
													layoutId: "tNpYKsbub",
													nHv9AZDwv: "Launch, Optimize, Scale",
													Qmh6a_4RQ:
														"We implement, monitor, and optimize your campaigns in real-time so you see\xA0results\xA0faster.",
													style: {
														width: "100%",
													},
													width: "100%",
													Y3xZTreNR: addImageAlt(
														{
															pixelHeight: 3615,
															pixelWidth: 6e3,
															src: "https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?width=6000&height=3615",
															srcSet:
																"https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?scale-down-to=512&width=6000&height=3615 512w,https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?scale-down-to=1024&width=6000&height=3615 1024w,https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?scale-down-to=2048&width=6000&height=3615 2048w,https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?scale-down-to=4096&width=6000&height=3615 4096w,https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?width=6000&height=3615 6000w",
														},
														"Envelope containing recommendations like \u201CFix churn spike\u201D and \u201CAction,\u201D symbolizing actionable insights.",
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
									</motion2.div>
								</motion2.div>
							</motion2.div>
						)}
						{isDisplayed1() && (
							<motion2.div
								className={"framer-vmv4v5"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"RRdvS4H5o"}
							>
								<ComponentViewportProvider
									height={207}
									width={`calc(min(${componentViewport?.width || "100vw"}, 1200px) - 96px)`}
									y={
										(componentViewport?.y || 0) +
										100 +
										(((componentViewport?.height || 840) - 200 - 659) / 2 +
											0 +
											0) +
										0 +
										0
									}
								>
									<SmartComponentScopedContainer
										className={"framer-1ke52u8-container"}
										layoutDependency={layoutDependency}
										layoutId={"YR4hDTBF5-container"}
										nodeId={"YR4hDTBF5"}
										rendersWithMotion={true}
										scopeId={"VsPxQDi0B"}
									>
										{_jsx2(stdin_default, {
											height: "100%",
											id: "YR4hDTBF5",
											layoutId: "YR4hDTBF5",
											LZ8_yaAGB: "Get clear answers in 3 simple steps",
											style: {
												width: "100%",
											},
											sWnc4R5C9:
												"From data to clarity\u2014uncover insights, take action, and grow smarter in three simple steps.",
											variant: "GCevxSqGm",
											width: "100%",
											ZBMvVPx0w: "How It Works",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion2.div
									className={"framer-fuo865"}
									data-framer-name={"Cards"}
									layoutDependency={layoutDependency}
									layoutId={"YYDf7VVd8"}
								>
									<ComponentViewportProvider
										height={42}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 840) - 200 - 659) / 2 +
												0 +
												0) +
											0 +
											263 +
											0 +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-t0p4dd-container"}
											layoutDependency={layoutDependency}
											layoutId={"UZRru5Uc3-container"}
											nodeId={"UZRru5Uc3"}
											rendersWithMotion={true}
											scopeId={"VsPxQDi0B"}
										>
											{_jsx2(stdin_default2, {
												e5w0UxZNt:
													"https://framer.com/remix/sYqnVgaJ6jfdOyaORZkY",
												height: "100%",
												hKzSQEl_0: "Claim Free AI Call",
												id: "UZRru5Uc3",
												layoutId: "UZRru5Uc3",
												VEpndFiaz: true,
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<motion2.div
										className={"framer-101id64"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"iFJfJK2ER"}
									>
										<ComponentViewportProvider
											height={330}
											width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 50px)`}
											y={
												(componentViewport?.y || 0) +
												100 +
												(((componentViewport?.height || 840) - 200 - 659) / 2 +
													0 +
													0) +
												0 +
												263 +
												0 +
												66 +
												0 +
												0
											}
										>
											<SmartComponentScopedContainerWithFX
												__framer__animate={{
													transition: transition2,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0.5}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-1s5jukj-container"}
												layoutDependency={layoutDependency}
												layoutId={"SlkhiWD6r-container"}
												nodeId={"SlkhiWD6r"}
												rendersWithMotion={true}
												scopeId={"VsPxQDi0B"}
											>
												{_jsx2(stdin_default3, {
													height: "100%",
													id: "SlkhiWD6r",
													layoutId: "SlkhiWD6r",
													nHv9AZDwv: "Book a Free Strategy Call",
													Qmh6a_4RQ:
														"Tell us about your goals. We\u2019ll show you how AI can get you there faster.",
													style: {
														width: "100%",
													},
													width: "100%",
													Y3xZTreNR: addImageAlt(
														{
															pixelHeight: 1080,
															pixelWidth: 1080,
															src: "https://framerusercontent.com/images/Do62WUItr7MQr0OG0a3kR6XhS0.png?width=1080&height=1080",
															srcSet:
																"https://framerusercontent.com/images/Do62WUItr7MQr0OG0a3kR6XhS0.png?scale-down-to=512&width=1080&height=1080 512w,https://framerusercontent.com/images/Do62WUItr7MQr0OG0a3kR6XhS0.png?scale-down-to=1024&width=1080&height=1080 1024w,https://framerusercontent.com/images/Do62WUItr7MQr0OG0a3kR6XhS0.png?width=1080&height=1080 1080w",
														},
														"Logos of tools outward, illustrating easy integration with no engineering required.",
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={330}
											width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 50px)`}
											y={
												(componentViewport?.y || 0) +
												100 +
												(((componentViewport?.height || 840) - 200 - 659) / 2 +
													0 +
													0) +
												0 +
												263 +
												0 +
												66 +
												0 +
												0
											}
										>
											<SmartComponentScopedContainerWithFX
												__framer__animate={{
													transition: transition3,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0.5}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-1d8w9r0-container"}
												layoutDependency={layoutDependency}
												layoutId={"pZtnLolrm-container"}
												nodeId={"pZtnLolrm"}
												rendersWithMotion={true}
												scopeId={"VsPxQDi0B"}
											>
												{_jsx2(stdin_default3, {
													height: "100%",
													id: "pZtnLolrm",
													layoutId: "pZtnLolrm",
													nHv9AZDwv: "AI-Powered Growth Plan",
													Qmh6a_4RQ:
														"We build a custom roadmap using data, automation, and personalization tools tailored to your business.",
													style: {
														width: "100%",
													},
													width: "100%",
													Y3xZTreNR: addImageAlt(
														{
															pixelHeight: 3528,
															pixelWidth: 6e3,
															src: "https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?width=6000&height=3528",
															srcSet:
																"https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?scale-down-to=512&width=6000&height=3528 512w,https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?scale-down-to=1024&width=6000&height=3528 1024w,https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?scale-down-to=2048&width=6000&height=3528 2048w,https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?scale-down-to=4096&width=6000&height=3528 4096w,https://framerusercontent.com/images/MTi16xQQXh1uLFK6rlUiLRrhNc4.png?width=6000&height=3528 6000w",
														},
														"Gauge showing levels of user engagement, with tags for high and low engagement percentages.",
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={330}
											width={`max((min(${componentViewport?.width || "100vw"}, 1200px) - 136px) / 3, 50px)`}
											y={
												(componentViewport?.y || 0) +
												100 +
												(((componentViewport?.height || 840) - 200 - 659) / 2 +
													0 +
													0) +
												0 +
												263 +
												0 +
												66 +
												0 +
												0
											}
										>
											<SmartComponentScopedContainerWithFX
												__framer__animate={{
													transition: transition4,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0.5}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-ml7zwx-container"}
												layoutDependency={layoutDependency}
												layoutId={"A6gCQUA6O-container"}
												nodeId={"A6gCQUA6O"}
												rendersWithMotion={true}
												scopeId={"VsPxQDi0B"}
											>
												{_jsx2(stdin_default3, {
													height: "100%",
													id: "A6gCQUA6O",
													layoutId: "A6gCQUA6O",
													nHv9AZDwv: "Launch, Optimize, Scale",
													Qmh6a_4RQ:
														"We implement, monitor, and optimize your campaigns in real-time so you see\xA0results\xA0faster.",
													style: {
														width: "100%",
													},
													width: "100%",
													Y3xZTreNR: addImageAlt(
														{
															pixelHeight: 3615,
															pixelWidth: 6e3,
															src: "https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?width=6000&height=3615",
															srcSet:
																"https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?scale-down-to=512&width=6000&height=3615 512w,https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?scale-down-to=1024&width=6000&height=3615 1024w,https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?scale-down-to=2048&width=6000&height=3615 2048w,https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?scale-down-to=4096&width=6000&height=3615 4096w,https://framerusercontent.com/images/WVfMImGvfZB1ZvVOi4f8QpGgcQ.png?width=6000&height=3615 6000w",
														},
														"Envelope containing recommendations like \u201CFix churn spike\u201D and \u201CAction,\u201D symbolizing actionable insights.",
													),
												})}
											</SmartComponentScopedContainerWithFX>
										</ComponentViewportProvider>
									</motion2.div>
								</motion2.div>
							</motion2.div>
						)}
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-u9Jop.framer-11lv7hx, .framer-u9Jop .framer-11lv7hx { display: block; }",
	".framer-u9Jop.framer-1ijbfk9 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 80px 0px 80px 0px; position: relative; width: 100%; max-width: 1200px; margin: 0 auto; }",
	".framer-u9Jop .framer-r24pfz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 43px; height: 1px; justify-content: flex-start; overflow: visible; padding: 39px 48px 39px 48px; position: relative; width: 390px; }",
	".framer-u9Jop .framer-rlg4ba-container, .framer-u9Jop .framer-1uh8ceh-container, .framer-u9Jop .framer-yvz6jw-container, .framer-u9Jop .framer-1n40rvw-container, .framer-u9Jop .framer-1ke52u8-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-u9Jop .framer-lf1le0, .framer-u9Jop .framer-fuo865 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-u9Jop .framer-izbof6-container, .framer-u9Jop .framer-t0p4dd-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-u9Jop .framer-kjtfav { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px 20px; height: auto; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 300px; }",
	".framer-u9Jop .framer-vmv4v5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px 48px 0px 48px; position: relative; width: 100%; }",
	".framer-u9Jop .framer-101id64 { display: grid; flex: none; gap: 20px 20px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(3, minmax(50px, 1fr)); grid-template-rows: repeat(1, minmax(0, 1fr)); height: auto; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-u9Jop .framer-1s5jukj-container, .framer-u9Jop .framer-1d8w9r0-container, .framer-u9Jop .framer-ml7zwx-container { align-self: start; flex: none; height: 100%; justify-self: start; position: relative; width: 100%; }",
	".framer-u9Jop.framer-v-1mxeaak.framer-1ijbfk9 { height: auto; width: 100%; max-width: 100%; }",
	"@media (max-width: 768px) { .framer-u9Jop.framer-1ijbfk9 { margin: 0 auto; padding: 60px 0px 60px 0px; position: relative; z-index: 1; } }",
	"@media (max-width: 768px) { .framer-u9Jop .framer-101id64 { grid-template-columns: 1fr; gap: 16px 16px; } }",
	"@media (max-width: 768px) { .framer-u9Jop .framer-kjtfav { width: 100%; } }",
	"@media (max-width: 768px) { .framer-u9Jop .framer-vmv4v5 { padding: 0px 16px 0px 16px; } }",
	"@media (max-width: 768px) { .framer-u9Jop .framer-r24pfz { width: 100%; padding: 24px 16px 24px 16px; } }",
	".framer-u9Jop.framer-v-1mxeaak .framer-r24pfz { order: 0; }",
];
var FramerVsPxQDi0B = withCSS2(Component2, css4, "framer-u9Jop");
var stdin_default4 = FramerVsPxQDi0B;
FramerVsPxQDi0B.displayName = "How it works";
FramerVsPxQDi0B.defaultProps = {
	height: 840,
	width: 1200,
};
addPropertyControls2(FramerVsPxQDi0B, {
	variant: {
		options: ["LhC4b14kZ", "J3vv7CwRw"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	vVTdAHXlT: {
		defaultValue:
			"From data to clarity\u2014uncover insights, take action, and grow smarter in three simple steps.",
		displayTextArea: false,
		title: "Text",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerVsPxQDi0B,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...SeperatorFonts,
		...ButtonFonts,
		...HowItWorksFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:how-it-works
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "LhC4b14kZ",
	xl: "LhC4b14kZ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HowItWorksFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var how_it_works_default = ComponentWithRoot;
export { how_it_works_default as default };
