// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ac4b2f1e7a67ec54 "Alytics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Ticker } from "./chunks/chunk-DUXOTEEB.js";
import { Icon } from "./chunks/chunk-BTSBQWPZ.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-EH5635TV.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
	stdin_default,
} from "./chunks/chunk-XAKJVEAV.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-JCMURR45.js";
import { className, css, fonts } from "./chunks/chunk-T7ZDJKBY.js";
import { routes } from "./chunks/chunk-D3NEX6SN.js";

// virtual:integrations
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Z050lKXYmJd7lkopEevM/NQQ0OhXq29CNROVbSnK2/lqHQIr9vh.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider3,
	ControlType as ControlType3,
	cx as cx3,
	getFonts as getFonts3,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer3,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/iP4CQFhKZMmZVJ5NE84O/A6rQhN8pRPOcIDdrs09S/jQn4elHMP.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/oS0ruowhkdDmYw7HKO2B/mqrFug3QboIT7vY0tlsK/L7CUivWhY.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getPropertyControls,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var PhosphorControls = getPropertyControls(Icon);
var cycleOrder = ["lTeSMKRAK", "JjvHJVyH3"];
var serializationHash = "framer-b383P";
var variantClassNames = {
	JjvHJVyH3: "framer-v-1ye95si",
	lTeSMKRAK: "framer-v-14iz01w",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"01": "lTeSMKRAK",
	"02": "JjvHJVyH3",
};
var getProps = ({
	fill,
	height,
	icon,
	iconColor,
	id,
	shadowBorder,
	width,
	...props
}) => {
	return {
		...props,
		b5zt00dtl:
			fill ??
			props.b5zt00dtl ??
			"var(--token-469374a6-bb69-4bd2-9e1b-0aebf435f73e, rgb(248, 248, 248))",
		HxHsYZRzW:
			iconColor ??
			props.HxHsYZRzW ??
			"var(--token-cb2243e7-371d-4dd4-a3f5-00f97c4730ab, rgb(87, 87, 87))",
		MdulmXBYe: icon ?? props.MdulmXBYe ?? "Check",
		qQjgnRstX:
			shadowBorder ??
			props.qQjgnRstX ??
			"0px 0px 0px 1px var(--token-a0d7c77d-bb42-477c-affc-b56f45ae9a8a, rgb(235, 235, 235))",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "lTeSMKRAK",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		MdulmXBYe,
		HxHsYZRzW,
		b5zt00dtl,
		qQjgnRstX,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lTeSMKRAK",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-14iz01w",
							className4,
							classNames,
						)}
						data-framer-name={"01"}
						layoutDependency={layoutDependency}
						layoutId={"lTeSMKRAK"}
						ref={refBinding}
						style={{
							"--3vus6i": qQjgnRstX,
							backgroundColor: b5zt00dtl,
							borderBottomLeftRadius: 50,
							borderBottomRightRadius: 50,
							borderTopLeftRadius: 50,
							borderTopRightRadius: 50,
							boxShadow: "var(--3vus6i)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								JjvHJVyH3: {
									"data-framer-name": "02",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1g3evrw-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"WtOx6XMC8-container"}
								nodeId={"WtOx6XMC8"}
								rendersWithMotion={true}
								scopeId={"L7CUivWhY"}
							>
								<Icon
									color={HxHsYZRzW}
									height={"100%"}
									iconSearch={"House"}
									iconSelection={MdulmXBYe}
									id={"WtOx6XMC8"}
									layoutId={"WtOx6XMC8"}
									mirrored={false}
									selectByList={true}
									style={{
										height: "100%",
										width: "100%",
									}}
									weight={"bold"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-b383P.framer-ujau55, .framer-b383P .framer-ujau55 { display: block; }",
	".framer-b383P.framer-14iz01w { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 23px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 22px; will-change: var(--framer-will-change-override, transform); }",
	".framer-b383P .framer-1g3evrw-container { flex: none; height: 14px; position: relative; width: 14px; }",
	".framer-b383P.framer-v-1ye95si.framer-14iz01w { height: 12px; width: 12px; }",
	".framer-b383P.framer-v-1ye95si .framer-1g3evrw-container { height: 12px; width: 8px; }",
];
var FramerL7CUivWhY = withCSS(Component, css4, "framer-b383P");
var stdin_default3 = FramerL7CUivWhY;
FramerL7CUivWhY.displayName = "Icon";
FramerL7CUivWhY.defaultProps = {
	height: 22,
	width: 22,
};
addPropertyControls(FramerL7CUivWhY, {
	variant: {
		options: ["lTeSMKRAK", "JjvHJVyH3"],
		optionTitles: ["01", "02"],
		title: "Variant",
		type: ControlType.Enum,
	},
	MdulmXBYe: PhosphorControls?.["iconSelection"] && {
		...PhosphorControls["iconSelection"],
		defaultValue: "Check",
		description: void 0,
		hidden: void 0,
		title: "Icon",
	},
	HxHsYZRzW: {
		defaultValue:
			'var(--token-cb2243e7-371d-4dd4-a3f5-00f97c4730ab, rgb(87, 87, 87)) /* {"name":"Text"} */',
		title: "Icon Color",
		type: ControlType.Color,
	},
	b5zt00dtl: {
		defaultValue:
			"var(--token-469374a6-bb69-4bd2-9e1b-0aebf435f73e, rgb(248, 248, 248))",
		title: "Fill",
		type: ControlType.Color,
	},
	qQjgnRstX: {
		defaultValue: [
			{
				blur: 0,
				color:
					'var(--token-a0d7c77d-bb42-477c-affc-b56f45ae9a8a, rgb(235, 235, 235)) /* {"name":"Stroke"} */',
				diffusion: 0.5,
				focus: 0.5,
				inset: false,
				spread: 1,
				type: "box",
				x: 0,
				y: 0,
			},
		],
		title: "Shadow border",
		type: ControlType.BoxShadow,
	},
});
addFonts(
	FramerL7CUivWhY,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...PhosphorFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/iP4CQFhKZMmZVJ5NE84O/A6rQhN8pRPOcIDdrs09S/jQn4elHMP.js
var IconFonts = getFonts2(stdin_default3);
var serializationHash2 = "framer-Hm2pI";
var variantClassNames2 = {
	Nv9w54iss: "framer-v-il3e6y",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, image, title, width, ...props }) => {
	return {
		...props,
		p9eghqI0h: image ?? props.p9eghqI0h,
		RPCDTAZiJ: title ?? props.RPCDTAZiJ ?? "Stripe",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		p9eghqI0h,
		RPCDTAZiJ,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "Nv9w54iss",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className3];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-il3e6y",
							className4,
							classNames,
						)}
						data-framer-name={"01"}
						layoutDependency={layoutDependency}
						layoutId={"Nv9w54iss"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
							borderBottomLeftRadius: 12,
							borderBottomRightRadius: 12,
							borderTopLeftRadius: 12,
							borderTopRightRadius: 12,
							boxShadow:
								"0px 0.6021873017743928px 0.421531111242075px -0.9166666666666666px rgba(0, 0, 0, 0.01), 0px 2.288533303243457px 1.60197331227042px -1.8333333333333333px rgba(0, 0, 0, 0.01), 0px 10px 7px -2.75px rgba(0, 0, 0, 0.01), 0px -0.6021873017743928px 0.421531111242075px -0.9166666666666666px rgba(0, 0, 0, 0.01), 0px -2.288533303243457px 1.60197331227042px -1.8333333333333333px rgba(0, 0, 0, 0.01), 0px -10px 7px -2.75px rgba(0, 0, 0, 0.01), 0.6021873017743928px 0px 0.6021873017743928px -1.1666666666666665px rgba(0, 0, 0, 0.01), 2.288533303243457px 0px 2.288533303243457px -2.333333333333333px rgba(0, 0, 0, 0.01), 10px 0px 10px -3.5px rgba(0, 0, 0, 0.01), -0.6021873017743928px 0px 0.6021873017743928px -1.1666666666666665px rgba(0, 0, 0, 0.01), -2.288533303243457px 0px 2.288533303243457px -2.333333333333333px rgba(0, 0, 0, 0.01), -10px 0px 10px -3.5px rgba(0, 0, 0, 0.01)",
							...style,
						}}
					>
						<motion2.div
							className={"framer-1ip2zmh"}
							data-framer-name={"Image container"}
							layoutDependency={layoutDependency}
							layoutId={"xmLIZ3xSG"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(8 + ((componentViewport?.height || 61) - 16 - 46) / 2) +
											0,
									),
									pixelHeight: 161,
									pixelWidth: 161,
									sizes: "45px",
									...toResponsiveImage(p9eghqI0h),
								}}
								className={"framer-l2e6yj"}
								layoutDependency={layoutDependency}
								layoutId={"LC14wvqNF"}
								style={{
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
								}}
							/>
						</motion2.div>
						<motion2.div
							className={"framer-gmi0k0"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"fWXXUUIFo"}
						>
							<motion2.div
								className={"framer-sfomhy"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"hi25q6XXx"}
							>
								<ComponentViewportProvider2
									height={22}
									y={
										(componentViewport?.y || 0) +
										(8 + ((componentViewport?.height || 61) - 16 - 46) / 2) +
										0 +
										0 +
										0
									}
								>
									<SmartComponentScopedContainer2
										className={"framer-1ekorof-container"}
										layoutDependency={layoutDependency}
										layoutId={"bAhHMst7F-container"}
										nodeId={"bAhHMst7F"}
										rendersWithMotion={true}
										scopeId={"jQn4elHMP"}
									>
										{_jsx2(stdin_default3, {
											b5zt00dtl:
												"var(--token-58f62a67-15de-4e6e-b079-00f80c0704c1, rgb(18, 109, 251))",
											height: "100%",
											HxHsYZRzW:
												"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
											id: "bAhHMst7F",
											layoutId: "bAhHMst7F",
											MdulmXBYe: "Check",
											qQjgnRstX:
												"0px 0px 0px 1px var(--token-563968fe-1dc6-43a4-93e9-d9bd53c68cc8, rgb(225, 234, 248))",
											variant: "JjvHJVyH3",
											width: "100%",
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1w3e2ey"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"N1Xzt5r7w"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e1ef367e-e23b-4a9e-826b-77a848c7f0b3, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={RPCDTAZiJ}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1p50hdg"}
											data-styles-preset={"ZL5MU_VZC"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e1ef367e-e23b-4a9e-826b-77a848c7f0b3, rgb(0, 0, 0)))",
											}}
										>
											{"Stripe"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
							<motion2.div
								className={"framer-20a4ek"}
								layoutDependency={layoutDependency}
								layoutId={"LwGpDlE5Y"}
							>
								<motion2.div
									className={"framer-1wfycwg"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"mHET2Gorh"}
									style={{
										backgroundColor:
											"var(--token-563968fe-1dc6-43a4-93e9-d9bd53c68cc8, rgb(225, 234, 248))",
										borderBottomLeftRadius: 10,
										borderBottomRightRadius: 10,
										borderTopLeftRadius: 10,
										borderTopRightRadius: 10,
									}}
								/>
								<motion2.div
									className={"framer-17k6ngj"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"sxAdyoCWw"}
									style={{
										backgroundColor:
											"var(--token-563968fe-1dc6-43a4-93e9-d9bd53c68cc8, rgb(225, 234, 248))",
										borderBottomLeftRadius: 10,
										borderBottomRightRadius: 10,
										borderTopLeftRadius: 10,
										borderTopRightRadius: 10,
									}}
								/>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Hm2pI.framer-1q0crd8, .framer-Hm2pI .framer-1q0crd8 { display: block; }",
	".framer-Hm2pI.framer-il3e6y { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-Hm2pI .framer-1ip2zmh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-Hm2pI .framer-l2e6yj { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 45px); overflow: hidden; position: relative; width: 45px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Hm2pI .framer-gmi0k0 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 173px; }",
	".framer-Hm2pI .framer-sfomhy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Hm2pI .framer-1ekorof-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-Hm2pI .framer-1w3e2ey { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Hm2pI .framer-20a4ek { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Hm2pI .framer-1wfycwg { flex: none; height: 7px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-Hm2pI .framer-17k6ngj { flex: none; height: 7px; overflow: hidden; position: relative; width: 122px; will-change: var(--framer-will-change-override, transform); }",
	...css3,
];
var FramerjQn4elHMP = withCSS2(Component2, css5, "framer-Hm2pI");
var stdin_default4 = FramerjQn4elHMP;
FramerjQn4elHMP.displayName = "Integration item";
FramerjQn4elHMP.defaultProps = {
	height: 61,
	width: 242,
};
addPropertyControls2(FramerjQn4elHMP, {
	p9eghqI0h: {
		title: "Image",
		type: ControlType2.ResponsiveImage,
	},
	RPCDTAZiJ: {
		defaultValue: "Stripe",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerjQn4elHMP,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...IconFonts,
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/Z050lKXYmJd7lkopEevM/NQQ0OhXq29CNROVbSnK2/lqHQIr9vh.js
var TagFonts = getFonts3(stdin_default);
var ButtonFonts = getFonts3(stdin_default2);
var IntegrationItemFonts = getFonts3(stdin_default4);
var TickerFonts = getFonts3(Ticker);
var MotionDivWithFX = withFX(motion3.div);
var cycleOrder2 = ["Cuvf1oZ36", "yuZvmtVIA"];
var serializationHash3 = "framer-dLeYE";
var variantClassNames3 = {
	Cuvf1oZ36: "framer-v-10of8j7",
	yuZvmtVIA: "framer-v-1kgzgy8",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 60,
	delay: 0.2,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var humanReadableVariantMap2 = {
	"Variant 1": "Cuvf1oZ36",
	"Variant 2": "yuZvmtVIA",
};
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "Cuvf1oZ36",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder2,
		defaultVariant: "Cuvf1oZ36",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.section
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-10of8j7",
							className4,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Cuvf1oZ36"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								yuZvmtVIA: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-1vv3f8m"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"TNuPf4bAS"}
						>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-4l03k1"}
								data-framer-name={"Integration"}
								layoutDependency={layoutDependency}
								layoutId={"dKqJQZpFg"}
								style={{
									backgroundColor:
										"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
									boxShadow: "0px 1px 20px 0px rgba(0, 0, 0, 0.03)",
								}}
							>
								<motion3.div
									className={"framer-shdkrm"}
									data-framer-name={"Left"}
									layoutDependency={layoutDependency}
									layoutId={"p2fvdltzo"}
								>
									<motion3.div
										className={"framer-1f3swug"}
										data-framer-name={"Content"}
										layoutDependency={layoutDependency}
										layoutId={"ElfXByjFG"}
									>
										<ComponentViewportProvider3
											height={30}
											y={
												(componentViewport?.y || 0) +
												100 +
												(((componentViewport?.height || 570) - 200 - 370) / 2 +
													0 +
													0) +
												0 +
												0 +
												65.15 +
												0 +
												0 +
												0 +
												0
											}
											{...addPropertyOverrides2(
												{
													yuZvmtVIA: {
														y:
															(componentViewport?.y || 0) +
															100 +
															(((componentViewport?.height || 900) -
																200 -
																700) /
																2 +
																0 +
																0) +
															0 +
															0 +
															40 +
															0 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer3
												className={"framer-ir8wck-container"}
												layoutDependency={layoutDependency}
												layoutId={"o2why3vIx-container"}
												nodeId={"o2why3vIx"}
												rendersWithMotion={true}
												scopeId={"lqHQIr9vh"}
											>
												{_jsx3(stdin_default, {
													height: "100%",
													id: "o2why3vIx",
													ITisGFbLK: "Integrations",
													layoutId: "o2why3vIx",
													width: "100%",
												})}
											</SmartComponentScopedContainer3>
										</ComponentViewportProvider3>
										<motion3.div
											className={"framer-jx1pb8"}
											data-framer-name={"Heading + Text"}
											layoutDependency={layoutDependency}
											layoutId={"kZtoFvkXj"}
										>
											<RichText2
												__fromCanvasComponent={true}
												className={"framer-w3yceu"}
												data-framer-name={"Heading"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"kXMny8M67"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React3.Fragment>
													<motion3.h2
														className={"framer-styles-preset-xrkfmc"}
														data-styles-preset={"v3uTk3d0Q"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{"Seamless Integrations with 1500+ Apps"}
													</motion3.h2>
												</React3.Fragment>
											</RichText2>
											<RichText2
												__fromCanvasComponent={true}
												className={"framer-10xfn4c"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"xBykD1RYQ"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React3.Fragment>
													<motion3.p
														className={"framer-styles-preset-oo9bt8"}
														data-styles-preset={"Qd8jNwk_8"}
														style={{
															"--framer-text-alignment": "left",
														}}
													>
														{
															"Seamlessly integrate AI2Market with 1,500+ tools to streamline your workflows."
														}
													</motion3.p>
												</React3.Fragment>
											</RichText2>
										</motion3.div>
									</motion3.div>
									<ComponentViewportProvider3
										height={42}
										y={
											(componentViewport?.y || 0) +
											100 +
											(((componentViewport?.height || 570) - 200 - 370) / 2 +
												0 +
												0) +
											0 +
											0 +
											65.15 +
											0 +
											197.7
										}
										{...addPropertyOverrides2(
											{
												yuZvmtVIA: {
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 900) - 200 - 700) /
															2 +
															0 +
															0) +
														0 +
														0 +
														40 +
														0 +
														0 +
														197.7,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer3
											className={"framer-mp5efq-container"}
											layoutDependency={layoutDependency}
											layoutId={"uvnDUuJl_-container"}
											nodeId={"uvnDUuJl_"}
											rendersWithMotion={true}
											scopeId={"lqHQIr9vh"}
										>
											{_jsx3(stdin_default2, {
												e5w0UxZNt:
													"https://framer.com/remix/sYqnVgaJ6jfdOyaORZkY",
												height: "100%",
												hKzSQEl_0: "Get Started Now",
												id: "uvnDUuJl_",
												layoutId: "uvnDUuJl_",
												VEpndFiaz: true,
												width: "100%",
											})}
										</SmartComponentScopedContainer3>
									</ComponentViewportProvider3>
								</motion3.div>
								<motion3.div
									className={"framer-121t7zf"}
									data-framer-name={"Ticker"}
									layoutDependency={layoutDependency}
									layoutId={"swF9jZ198"}
									style={{
										backgroundColor:
											"var(--token-469374a6-bb69-4bd2-9e1b-0aebf435f73e, rgb(248, 248, 248))",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
								>
									<ComponentViewportProvider3>
										<SmartComponentScopedContainer3
											className={"framer-18j5s51-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"yV6bDdGdf-container"}
											nodeId={"yV6bDdGdf"}
											rendersWithMotion={true}
											scopeId={"lqHQIr9vh"}
										>
											<Ticker
												alignment={"center"}
												direction={"top"}
												fadeOptions={{
													fadeAlpha: 0,
													fadeContent: false,
													fadeInset: 0,
													fadeWidth: 25,
													overflow: false,
												}}
												gap={20}
												height={"100%"}
												hoverFactor={1}
												id={"yV6bDdGdf"}
												layoutId={"yV6bDdGdf"}
												padding={10}
												paddingBottom={10}
												paddingLeft={10}
												paddingPerSide={false}
												paddingRight={10}
												paddingTop={10}
												sizingOptions={{
													heightType: true,
													widthType: true,
												}}
												slots={[
													<ComponentViewportProvider3
														height={61}
														width={"242px"}
													>
														<SmartComponentScopedContainer3
															className={"framer-ob118y-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"yaf72Xldi-container"}
															nodeId={"yaf72Xldi"}
															rendersWithMotion={true}
															scopeId={"lqHQIr9vh"}
														>
															{_jsx3(stdin_default4, {
																height: "100%",
																id: "yaf72Xldi",
																layoutId: "yaf72Xldi",
																p9eghqI0h: addImageAlt(
																	{
																		pixelHeight: 800,
																		pixelWidth: 800,
																		src: "https://framerusercontent.com/images/O1DXDhjNe7zVWe4UU2DlTPrVEw.svg?width=800&height=800",
																		srcSet:
																			"https://framerusercontent.com/images/O1DXDhjNe7zVWe4UU2DlTPrVEw.svg?scale-down-to=512&width=800&height=800 512w,https://framerusercontent.com/images/O1DXDhjNe7zVWe4UU2DlTPrVEw.svg?width=800&height=800 800w",
																	},
																	"Nuvio Logo",
																),
																RPCDTAZiJ: "Stripe",
																width: "100%",
															})}
														</SmartComponentScopedContainer3>
													</ComponentViewportProvider3>,
													<ComponentViewportProvider3 height={61}>
														<SmartComponentScopedContainer3
															className={"framer-65nu90-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"hceFTzs32-container"}
															nodeId={"hceFTzs32"}
															rendersWithMotion={true}
															scopeId={"lqHQIr9vh"}
														>
															{_jsx3(stdin_default4, {
																height: "100%",
																id: "hceFTzs32",
																layoutId: "hceFTzs32",
																p9eghqI0h: addImageAlt(
																	{
																		pixelHeight: 125,
																		pixelWidth: 110,
																		src: "https://framerusercontent.com/images/8VzUjt87oxjNyOii1BVwLhxiL0.svg?width=110&height=125",
																	},
																	"Shopify",
																),
																RPCDTAZiJ: "Shopify",
																width: "100%",
															})}
														</SmartComponentScopedContainer3>
													</ComponentViewportProvider3>,
													<ComponentViewportProvider3 height={61}>
														<SmartComponentScopedContainer3
															className={"framer-1ls5gjq-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"UWSkiCmce-container"}
															nodeId={"UWSkiCmce"}
															rendersWithMotion={true}
															scopeId={"lqHQIr9vh"}
														>
															{_jsx3(stdin_default4, {
																height: "100%",
																id: "UWSkiCmce",
																layoutId: "UWSkiCmce",
																p9eghqI0h: addImageAlt(
																	{
																		pixelHeight: 24,
																		pixelWidth: 24,
																		src: "https://framerusercontent.com/images/SFlBnXKJW0Q6eWW3hAecOsnKATA.svg?width=24&height=24",
																	},
																	"Knot logo",
																),
																RPCDTAZiJ: "Meta",
																width: "100%",
															})}
														</SmartComponentScopedContainer3>
													</ComponentViewportProvider3>,
													<ComponentViewportProvider3 height={61}>
														<SmartComponentScopedContainer3
															className={"framer-h06f1-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"MuPJ8e_TS-container"}
															nodeId={"MuPJ8e_TS"}
															rendersWithMotion={true}
															scopeId={"lqHQIr9vh"}
														>
															{_jsx3(stdin_default4, {
																height: "100%",
																id: "MuPJ8e_TS",
																layoutId: "MuPJ8e_TS",
																p9eghqI0h: addImageAlt(
																	{
																		pixelHeight: 31,
																		pixelWidth: 131,
																		positionX: "0%",
																		positionY: "50%",
																		src: "https://framerusercontent.com/images/XR2WwpYgT5I134HzAllPoEqDyM.svg?width=131&height=31",
																	},
																	"WHatsApp",
																),
																RPCDTAZiJ: "Whatsapp",
																width: "100%",
															})}
														</SmartComponentScopedContainer3>
													</ComponentViewportProvider3>,
												]}
												speed={40}
												style={{
													height: "100%",
													width: "100%",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer3>
									</ComponentViewportProvider3>
								</motion3.div>
							</MotionDivWithFX>
						</motion3.div>
					</motion3.section>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dLeYE.framer-1vvsw7g, .framer-dLeYE .framer-1vvsw7g { display: block; }",
	".framer-dLeYE.framer-10of8j7 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 80px 0px 40px 0px; position: relative; width: 100%; max-width: 1200px; margin: 0 auto; }",
	".framer-dLeYE .framer-1vv3f8m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px 48px 0px 48px; position: relative; width: 100%; }",
	".framer-dLeYE .framer-4l03k1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: hidden; padding: 40px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-dLeYE .framer-shdkrm { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-dLeYE .framer-1f3swug, .framer-dLeYE .framer-jx1pb8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-dLeYE .framer-ir8wck-container, .framer-dLeYE .framer-mp5efq-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-dLeYE .framer-w3yceu { flex: none; height: auto; max-width: 500px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-dLeYE .framer-10xfn4c { flex: none; height: auto; max-width: 380px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-dLeYE .framer-121t7zf { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-dLeYE .framer-18j5s51-container { flex: none; height: 290px; position: relative; width: 100%; z-index: 2; }",
	".framer-dLeYE .framer-ob118y-container, .framer-dLeYE .framer-65nu90-container, .framer-dLeYE .framer-1ls5gjq-container, .framer-dLeYE .framer-h06f1-container { height: auto; position: relative; width: auto; }",
	".framer-dLeYE.framer-v-1kgzgy8.framer-10of8j7 { height: auto; width: 100%; max-width: 100%; }",
	"@media (max-width: 768px) { .framer-dLeYE.framer-10of8j7 { padding: 60px 0px 60px 0px; margin: 0 auto; position: relative; z-index: 2; } }",
	"@media (max-width: 768px) { .framer-dLeYE .framer-1vv3f8m { padding: 0px 16px 0px 16px; gap: 40px; } }",
	"@media (max-width: 768px) { .framer-dLeYE .framer-4l03k1 { display: grid; grid-template-columns: 1fr; grid-auto-rows: minmax(0, 1fr); gap: 24px; height: auto; } }",
	"@media (max-width: 768px) { .framer-dLeYE .framer-shdkrm, .framer-dLeYE .framer-121t7zf { width: 100%; } }",
	"@media (max-width: 768px) { .framer-dLeYE .framer-121t7zf { height: 290px; justify-self: center; } }",
	".framer-dLeYE.framer-v-1kgzgy8 .framer-1vv3f8m { align-content: unset; align-items: unset; display: grid; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(1, minmax(50px, 1fr)); grid-template-rows: repeat(1, minmax(0, 1fr)); justify-content: center; }",
	".framer-dLeYE.framer-v-1kgzgy8 .framer-4l03k1 { align-content: unset; align-items: unset; align-self: start; display: grid; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(1, minmax(50px, 1fr)); grid-template-rows: repeat(2, minmax(0, 1fr)); height: auto; justify-self: start; }",
	".framer-dLeYE.framer-v-1kgzgy8 .framer-shdkrm { align-self: start; flex: none; justify-self: start; order: 0; width: 100%; }",
	".framer-dLeYE.framer-v-1kgzgy8 .framer-121t7zf { align-content: unset; align-items: unset; align-self: start; display: grid; flex: none; grid-auto-rows: minmax(0, 1fr); grid-column: span 1; grid-template-columns: repeat(1, minmax(50px, 1fr)); grid-template-rows: repeat(1, minmax(0, 1fr)); height: 290px; justify-self: center; order: 1; width: 268px; }",
	".framer-dLeYE.framer-v-1kgzgy8 .framer-18j5s51-container { align-self: start; height: 100%; justify-self: start; order: 0; }",
	...css2,
	...css,
];
var FramerlqHQIr9vh = withCSS3(Component3, css6, "framer-dLeYE");
var stdin_default5 = FramerlqHQIr9vh;
FramerlqHQIr9vh.displayName = "Integrations";
FramerlqHQIr9vh.defaultProps = {
	height: 570,
	width: 1200,
};
addPropertyControls3(FramerlqHQIr9vh, {
	variant: {
		options: ["Cuvf1oZ36", "yuZvmtVIA"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts3(
	FramerlqHQIr9vh,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TagFonts,
		...ButtonFonts,
		...IntegrationItemFonts,
		...TickerFonts,
		...getFontsFromSharedStyle2(fonts2),
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:integrations
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Cuvf1oZ36",
	xl: "Cuvf1oZ36",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IntegrationsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var integrations_default = ComponentWithRoot;
export { integrations_default as default };
