// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ac4b2f1e7a67ec54 "Alytics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile Close' | 'Mobile open' | 'Tab' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-XGOMNWJB.js";
import { className, css, fonts } from "./chunks/chunk-PUETUJTD.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-EH5635TV.js";
import "./chunks/chunk-T7ZDJKBY.js";
import { routes } from "./chunks/chunk-D3NEX6SN.js";

// virtual:navbar
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/pCocK5p6Z1lKdk4DiLbj/uO6vuwBfUdKf82G5Vr4G/FecD9Vbs3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Link1Fonts = getFonts(stdin_default);
var ButtonFonts = getFonts(stdin_default2);
var cycleOrder = ["IU0t15tN0", "XOAhPaRQv", "oUeFskBCG", "CLhUFy0B8"];
var serializationHash = "framer-UeD8Q";
var variantClassNames = {
	CLhUFy0B8: "framer-v-wgrps5",
	IU0t15tN0: "framer-v-av93at",
	oUeFskBCG: "framer-v-rlpz40",
	XOAhPaRQv: "framer-v-6dq2rg",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Mobile Close": "XOAhPaRQv",
	"Mobile open": "oUeFskBCG",
	Desktop: "IU0t15tN0",
	Tab: "CLhUFy0B8",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "IU0t15tN0",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IU0t15tN0",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapcp37j1 = activeVariantCallback(async (...args) => {
		setVariant("XOAhPaRQv");
	});
	const onTap1azpvld = activeVariantCallback(async (...args) => {
		setVariant("oUeFskBCG");
	});
	const a2Ti_6_Nlcp37j1 = activeVariantCallback(async (...args) => {
		setVariant("XOAhPaRQv");
	});
	const AD2msOAVkcp37j1 = activeVariantCallback(async (...args) => {
		setVariant("XOAhPaRQv");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["XOAhPaRQv", "oUeFskBCG"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "XOAhPaRQv") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.header
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-av93at",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						data-hide-scrollbars={true}
						layoutDependency={layoutDependency}
						layoutId={"IU0t15tN0"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
							boxShadow: "0px 1px 20px 0px rgba(0, 0, 0, 0.03)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								CLhUFy0B8: {
									"data-framer-name": "Tab",
								},
								oUeFskBCG: {
									"data-framer-name": "Mobile open",
								},
								XOAhPaRQv: {
									"data-framer-name": "Mobile Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1pmtxby"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"gB1ajrDFh"}
						>
							<motion.div
								className={"framer-1jsg3zd"}
								data-framer-name={"Name"}
								layoutDependency={layoutDependency}
								layoutId={"mcbmDyvWv"}
							>
								<Link
									href={{
										webPageId: "SiMIe5pOV",
									}}
									motionChild={true}
									nodeId={"CTiwSOcDt"}
									openInNewTab={false}
									scopeId={"FecD9Vbs3"}
									smoothScroll={true}
								>
									<motion.a
										className={"framer-1yq4hu3 framer-2see7u"}
										data-framer-name={"logo container"}
										layoutDependency={layoutDependency}
										layoutId={"CTiwSOcDt"}
										{...addPropertyOverrides(
											{
												oUeFskBCG: {
													"data-highlight": true,
													onTap: onTapcp37j1,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<Image
											background={{
												alt: "",
												fit: "fill",
												intrinsicHeight: 1188.8,
												intrinsicWidth: 2257.6,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(12 +
															((componentViewport?.height || 66) - 24 - 42) /
																2) +
														6.6 +
														0 +
														0.4,
												),
												pixelHeight: 1486,
												pixelWidth: 2822,
												sizes: "56px",
												src: "https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486",
												srcSet:
													"https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=512&width=2822&height=1486 512w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=1024&width=2822&height=1486 1024w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=2048&width=2822&height=1486 2048w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486 2822w",
											}}
											className={"framer-1sz4uqn"}
											data-framer-name={"AI2MARKETLOGO"}
											layoutDependency={layoutDependency}
											layoutId={"B0EH0lCGK"}
											{...addPropertyOverrides(
												{
													oUeFskBCG: {
														background: {
															alt: "",
															fit: "fill",
															intrinsicHeight: 1188.8,
															intrinsicWidth: 2257.6,
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	12 +
																	(((componentViewport?.height || 416) -
																		32 -
																		384) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0.6 +
																	0.4,
															),
															pixelHeight: 1486,
															pixelWidth: 2822,
															sizes: "56px",
															src: "https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486",
															srcSet:
																"https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=512&width=2822&height=1486 512w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=1024&width=2822&height=1486 1024w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=2048&width=2822&height=1486 2048w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486 2822w",
														},
													},
													XOAhPaRQv: {
														background: {
															alt: "",
															fit: "fill",
															intrinsicHeight: 1188.8,
															intrinsicWidth: 2257.6,
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	12 +
																	(((componentViewport?.height || 54) -
																		24 -
																		30) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0.6 +
																	0.4,
															),
															pixelHeight: 1486,
															pixelWidth: 2822,
															sizes: "56px",
															src: "https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486",
															srcSet:
																"https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=512&width=2822&height=1486 512w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=1024&width=2822&height=1486 1024w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?scale-down-to=2048&width=2822&height=1486 2048w,https://framerusercontent.com/images/jAzYvVQ7dDeHSCkzaTpsfy4V7VA.png?width=2822&height=1486 2822w",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1xdkg5e"}
											data-framer-name={"title"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"JZW2uX47r"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h4
													className={"framer-styles-preset-nrofro"}
													data-styles-preset={"egFybnJEl"}
												>
													{"AI2Market"}
												</motion.h4>
											</React.Fragment>
										</RichText>
									</motion.a>
								</Link>
								{isDisplayed() && (
									<motion.div
										className={"framer-7syrcc"}
										data-border={true}
										data-framer-name={"Hamburger"}
										layoutDependency={layoutDependency}
										layoutId={"EpdWA4EKk"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-a0d7c77d-bb42-477c-affc-b56f45ae9a8a, rgb(235, 235, 235))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor:
												"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
											borderBottomLeftRadius: 6,
											borderBottomRightRadius: 6,
											borderTopLeftRadius: 6,
											borderTopRightRadius: 6,
										}}
										{...addPropertyOverrides(
											{
												oUeFskBCG: {
													"data-highlight": true,
													onTap: onTapcp37j1,
												},
												XOAhPaRQv: {
													"data-highlight": true,
													onTap: onTap1azpvld,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion.div
											className={"framer-o97xiv"}
											data-framer-name={"Bottom"}
											layoutDependency={layoutDependency}
											layoutId={"uMrRhteo4"}
											style={{
												backgroundColor:
													"var(--token-58f62a67-15de-4e6e-b079-00f80c0704c1, rgb(18, 109, 251))",
												borderBottomLeftRadius: 10,
												borderBottomRightRadius: 10,
												borderTopLeftRadius: 10,
												borderTopRightRadius: 10,
												rotate: 0,
											}}
											variants={{
												oUeFskBCG: {
													rotate: -45,
												},
											}}
										/>
										<motion.div
											className={"framer-1g8kg2m"}
											data-framer-name={"Top"}
											layoutDependency={layoutDependency}
											layoutId={"DSfLuJQEi"}
											style={{
												backgroundColor:
													"var(--token-58f62a67-15de-4e6e-b079-00f80c0704c1, rgb(18, 109, 251))",
												borderBottomLeftRadius: 10,
												borderBottomRightRadius: 10,
												borderTopLeftRadius: 10,
												borderTopRightRadius: 10,
												rotate: 0,
											}}
											variants={{
												oUeFskBCG: {
													rotate: 45,
												},
											}}
										/>
									</motion.div>
								)}
							</motion.div>
							{isDisplayed1() && (
								<motion.nav
									className={"framer-1a1p95l"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"Oh81erxJp"}
								>
									<ResolveLinks
										links={[
											{
												href: {
													hash: ":dcyOO2PSB",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":dcyOO2PSB",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":dcyOO2PSB",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													(12 +
														((componentViewport?.height || 66) - 24 - 42) / 2) +
													1 +
													0
												}
												{...addPropertyOverrides(
													{
														oUeFskBCG: {
															width: `min(${componentViewport?.width || "100vw"} - 32px, 358px)`,
															y:
																(componentViewport?.y || 0) +
																12 +
																(((componentViewport?.height || 416) -
																	32 -
																	384) /
																	2 +
																	0 +
																	0) +
																0 +
																50 +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-l4h9o5-container"}
													layoutDependency={layoutDependency}
													layoutId={"eOZn4NVcc-container"}
													nodeId={"eOZn4NVcc"}
													rendersWithMotion={true}
													scopeId={"FecD9Vbs3"}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "eOZn4NVcc",
														layoutId: "eOZn4NVcc",
														mSvV0D8Pz: "Features",
														SdWgTx6ev: resolvedLinks[0],
														width: "100%",
														...addPropertyOverrides(
															{
																CLhUFy0B8: {
																	SdWgTx6ev: resolvedLinks[2],
																},
																oUeFskBCG: {
																	a2Ti_6_Nl: a2Ti_6_Nlcp37j1,
																	SdWgTx6ev: resolvedLinks[1],
																	style: {
																		width: "100%",
																	},
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													hash: ":Jn3wngbgL",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":Jn3wngbgL",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":Jn3wngbgL",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													(12 +
														((componentViewport?.height || 66) - 24 - 42) / 2) +
													1 +
													0
												}
												{...addPropertyOverrides(
													{
														oUeFskBCG: {
															width: `min(${componentViewport?.width || "100vw"} - 32px, 358px)`,
															y:
																(componentViewport?.y || 0) +
																12 +
																(((componentViewport?.height || 416) -
																	32 -
																	384) /
																	2 +
																	0 +
																	0) +
																0 +
																50 +
																0 +
																50,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-ej3yko-container"}
													layoutDependency={layoutDependency}
													layoutId={"FpWAIYxMe-container"}
													nodeId={"FpWAIYxMe"}
													rendersWithMotion={true}
													scopeId={"FecD9Vbs3"}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "FpWAIYxMe",
														layoutId: "FpWAIYxMe",
														mSvV0D8Pz: "Benefits",
														SdWgTx6ev: resolvedLinks1[0],
														width: "100%",
														...addPropertyOverrides(
															{
																CLhUFy0B8: {
																	SdWgTx6ev: resolvedLinks1[2],
																},
																oUeFskBCG: {
																	a2Ti_6_Nl: a2Ti_6_Nlcp37j1,
																	SdWgTx6ev: resolvedLinks1[1],
																	style: {
																		width: "100%",
																	},
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													hash: ":Cuvf1oZ36",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":Cuvf1oZ36",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":Cuvf1oZ36",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks2) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													(12 +
														((componentViewport?.height || 66) - 24 - 42) / 2) +
													1 +
													0
												}
												{...addPropertyOverrides(
													{
														oUeFskBCG: {
															width: `min(${componentViewport?.width || "100vw"} - 32px, 358px)`,
															y:
																(componentViewport?.y || 0) +
																12 +
																(((componentViewport?.height || 416) -
																	32 -
																	384) /
																	2 +
																	0 +
																	0) +
																0 +
																50 +
																0 +
																100,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1n5cc5s-container"}
													layoutDependency={layoutDependency}
													layoutId={"LSaiFG2sY-container"}
													nodeId={"LSaiFG2sY"}
													rendersWithMotion={true}
													scopeId={"FecD9Vbs3"}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "LSaiFG2sY",
														layoutId: "LSaiFG2sY",
														mSvV0D8Pz: "Integrations",
														SdWgTx6ev: resolvedLinks2[0],
														width: "100%",
														...addPropertyOverrides(
															{
																CLhUFy0B8: {
																	SdWgTx6ev: resolvedLinks2[2],
																},
																oUeFskBCG: {
																	a2Ti_6_Nl: a2Ti_6_Nlcp37j1,
																	SdWgTx6ev: resolvedLinks2[1],
																	style: {
																		width: "100%",
																	},
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													hash: ":rjsy3UbtH",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":rjsy3UbtH",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":rjsy3UbtH",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks3) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													(12 +
														((componentViewport?.height || 66) - 24 - 42) / 2) +
													1 +
													0
												}
												{...addPropertyOverrides(
													{
														oUeFskBCG: {
															width: `min(${componentViewport?.width || "100vw"} - 32px, 358px)`,
															y:
																(componentViewport?.y || 0) +
																12 +
																(((componentViewport?.height || 416) -
																	32 -
																	384) /
																	2 +
																	0 +
																	0) +
																0 +
																50 +
																0 +
																150,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-701ede-container"}
													layoutDependency={layoutDependency}
													layoutId={"XaE3LskWA-container"}
													nodeId={"XaE3LskWA"}
													rendersWithMotion={true}
													scopeId={"FecD9Vbs3"}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "XaE3LskWA",
														layoutId: "XaE3LskWA",
														mSvV0D8Pz: "Pricing",
														SdWgTx6ev: resolvedLinks3[0],
														width: "100%",
														...addPropertyOverrides(
															{
																CLhUFy0B8: {
																	SdWgTx6ev: resolvedLinks3[2],
																},
																oUeFskBCG: {
																	a2Ti_6_Nl: a2Ti_6_Nlcp37j1,
																	SdWgTx6ev: resolvedLinks3[1],
																	style: {
																		width: "100%",
																	},
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													hash: ":ntBUFNamL",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":ntBUFNamL",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":ntBUFNamL",
													webPageId: "SiMIe5pOV",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks4) => (
											<ComponentViewportProvider
												height={40}
												y={
													(componentViewport?.y || 0) +
													(12 +
														((componentViewport?.height || 66) - 24 - 42) / 2) +
													1 +
													0
												}
												{...addPropertyOverrides(
													{
														oUeFskBCG: {
															width: `min(${componentViewport?.width || "100vw"} - 32px, 358px)`,
															y:
																(componentViewport?.y || 0) +
																12 +
																(((componentViewport?.height || 416) -
																	32 -
																	384) /
																	2 +
																	0 +
																	0) +
																0 +
																50 +
																0 +
																200,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-gmtr11-container"}
													layoutDependency={layoutDependency}
													layoutId={"BFE_V9t3p-container"}
													nodeId={"BFE_V9t3p"}
													rendersWithMotion={true}
													scopeId={"FecD9Vbs3"}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "BFE_V9t3p",
														layoutId: "BFE_V9t3p",
														mSvV0D8Pz: "FAQ",
														SdWgTx6ev: resolvedLinks4[0],
														width: "100%",
														...addPropertyOverrides(
															{
																CLhUFy0B8: {
																	SdWgTx6ev: resolvedLinks4[2],
																},
																oUeFskBCG: {
																	a2Ti_6_Nl: a2Ti_6_Nlcp37j1,
																	SdWgTx6ev: resolvedLinks4[1],
																	style: {
																		width: "100%",
																	},
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion.nav>
							)}
							{isDisplayed1() && (
								<ComponentViewportProvider
									height={42}
									y={
										(componentViewport?.y || 0) +
										(12 + ((componentViewport?.height || 66) - 24 - 42) / 2) +
										0
									}
									{...addPropertyOverrides(
										{
											oUeFskBCG: {
												y:
													(componentViewport?.y || 0) +
													12 +
													(((componentViewport?.height || 416) - 32 - 384) / 2 +
														0 +
														0) +
													0 +
													310,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1yqfrnz-container"}
										layoutDependency={layoutDependency}
										layoutId={"LJun2PshA-container"}
										nodeId={"LJun2PshA"}
										rendersWithMotion={true}
										scopeId={"FecD9Vbs3"}
									>
										{_jsx(stdin_default2, {
											e5w0UxZNt:
												"https://framer.com/remix/sYqnVgaJ6jfdOyaORZkY",
											height: "100%",
											hKzSQEl_0: "Book a Free Audit",
											id: "LJun2PshA",
											layoutId: "LJun2PshA",
											VEpndFiaz: true,
											width: "100%",
											...addPropertyOverrides(
												{
													oUeFskBCG: {
														AD2msOAVk: AD2msOAVkcp37j1,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion.div>
					</motion.header>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UeD8Q.framer-2see7u, .framer-UeD8Q .framer-2see7u { display: block; }",
	".framer-UeD8Q.framer-av93at { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 12px 48px 12px 48px; position: relative; width: 1200px; }",
	".framer-UeD8Q .framer-1pmtxby { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1104px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-UeD8Q .framer-1jsg3zd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-UeD8Q .framer-1yq4hu3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-UeD8Q .framer-1sz4uqn { aspect-ratio: 1.899057873485868 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 30px); overflow: visible; position: relative; width: 56px; }",
	".framer-UeD8Q .framer-1xdkg5e { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-UeD8Q .framer-7syrcc { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 30px); overflow: hidden; position: relative; width: 30px; will-change: var(--framer-will-change-override, transform); }",
	".framer-UeD8Q .framer-o97xiv { flex: none; height: 2px; left: calc(50.00000000000002% - 18px / 2); overflow: hidden; position: absolute; top: calc(62.50000000000002% - 2px / 2); width: 18px; will-change: var(--framer-will-change-override, transform); }",
	".framer-UeD8Q .framer-1g8kg2m { flex: none; height: 2px; left: calc(50.00000000000002% - 18px / 2); overflow: hidden; position: absolute; top: calc(37.50000000000002% - 2px / 2); width: 18px; will-change: var(--framer-will-change-override, transform); }",
	".framer-UeD8Q .framer-1a1p95l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-UeD8Q .framer-l4h9o5-container, .framer-UeD8Q .framer-ej3yko-container, .framer-UeD8Q .framer-1n5cc5s-container, .framer-UeD8Q .framer-701ede-container, .framer-UeD8Q .framer-gmtr11-container, .framer-UeD8Q .framer-1yqfrnz-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-UeD8Q.framer-v-6dq2rg.framer-av93at { flex-direction: column; gap: 0px; padding: 12px 16px 12px 16px; width: 390px; }",
	".framer-UeD8Q.framer-v-6dq2rg .framer-1pmtxby { flex: none; flex-direction: column; gap: 20px; justify-content: flex-start; max-width: 358px; width: 100%; }",
	".framer-UeD8Q.framer-v-6dq2rg .framer-1jsg3zd, .framer-UeD8Q.framer-v-rlpz40 .framer-1jsg3zd { gap: unset; justify-content: space-between; width: 100%; }",
	".framer-UeD8Q.framer-v-6dq2rg .framer-7syrcc, .framer-UeD8Q.framer-v-rlpz40 .framer-1yq4hu3, .framer-UeD8Q.framer-v-rlpz40 .framer-7syrcc { cursor: pointer; }",
	".framer-UeD8Q.framer-v-rlpz40.framer-av93at { flex-direction: column; gap: 0px; max-height: calc(var(--framer-viewport-height, 100vh) * 1); padding: 12px 16px 20px 16px; width: 390px; }",
	".framer-UeD8Q.framer-v-rlpz40 .framer-1pmtxby { flex: none; flex-direction: column; gap: 20px; justify-content: flex-start; max-width: 358px; padding: 0px 0px 32px 0px; width: 100%; }",
	".framer-UeD8Q.framer-v-rlpz40 .framer-1sz4uqn, .framer-UeD8Q.framer-v-wgrps5 .framer-1sz4uqn { height: var(--framer-aspect-ratio-supported, 4px); }",
	".framer-UeD8Q.framer-v-rlpz40 .framer-o97xiv, .framer-UeD8Q.framer-v-rlpz40 .framer-1g8kg2m { top: calc(50.00000000000002% - 2px / 2); }",
	".framer-UeD8Q.framer-v-rlpz40 .framer-1a1p95l { flex-direction: column; width: 100%; }",
	".framer-UeD8Q.framer-v-rlpz40 .framer-l4h9o5-container, .framer-UeD8Q.framer-v-rlpz40 .framer-ej3yko-container, .framer-UeD8Q.framer-v-rlpz40 .framer-1n5cc5s-container, .framer-UeD8Q.framer-v-rlpz40 .framer-701ede-container, .framer-UeD8Q.framer-v-rlpz40 .framer-gmtr11-container { width: 100%; }",
	".framer-UeD8Q.framer-v-wgrps5.framer-av93at { padding: 12px 32px 12px 32px; width: 810px; }",
	".framer-UeD8Q.framer-v-wgrps5 .framer-1pmtxby { max-width: 748px; }",
	...css,
	'.framer-UeD8Q[data-hide-scrollbars="true"]::-webkit-scrollbar, .framer-UeD8Q [data-hide-scrollbars="true"]::-webkit-scrollbar { width: 0px; height: 0px; }',
	'.framer-UeD8Q[data-hide-scrollbars="true"]::-webkit-scrollbar-thumb, .framer-UeD8Q [data-hide-scrollbars="true"]::-webkit-scrollbar-thumb { background: transparent; }',
	'.framer-UeD8Q[data-hide-scrollbars="true"], .framer-UeD8Q [data-hide-scrollbars="true"] { scrollbar-width: none; }',
	'.framer-UeD8Q[data-border="true"]::after, .framer-UeD8Q [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerFecD9Vbs3 = withCSS(Component, css2, "framer-UeD8Q");
var stdin_default3 = FramerFecD9Vbs3;
FramerFecD9Vbs3.displayName = "Navbar";
FramerFecD9Vbs3.defaultProps = {
	height: 66,
	width: 1200,
};
addPropertyControls(FramerFecD9Vbs3, {
	variant: {
		options: ["IU0t15tN0", "XOAhPaRQv", "oUeFskBCG", "CLhUFy0B8"],
		optionTitles: ["Desktop", "Mobile Close", "Mobile open", "Tab"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerFecD9Vbs3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...Link1Fonts,
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navbar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XOAhPaRQv",
	md: "CLhUFy0B8",
	xl: "IU0t15tN0",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavbarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var navbar_default = ComponentWithRoot;
export { navbar_default as default };
