// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ac4b2f1e7a67ec54 "Alytics (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-EH5635TV.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-JCMURR45.js";
import { className, css, fonts } from "./chunks/chunk-T7ZDJKBY.js";
import { routes } from "./chunks/chunk-D3NEX6SN.js";

// virtual:newsletter
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/fXb07PP7yomH4X83fOOv/J4gNM5tonKrmA21GiSPN/jR40kgUaq.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/2wQFCJqtzYGgrPuGnouv/hX0FTfHhrrUJWNiyhFUj/aEzDQzBLB.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Geist-600",
	"Inter-Black",
	"Inter-BlackItalic",
	"Inter-BoldItalic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Geist",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geist/v3/gyBhhwUxId8gMGYQMKR3pzfaWI_RQuQ4mJPby1QNtA.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/mkY5Sgyq51ik0AMrSBwhm9DJg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/X5hj6qzcHUYv7h1390c8Rhm6550.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/gQhNpS3tN86g8RcVKYUUaKt2oMQ.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cugnVhSraaRyANCaUtI5FV17wk.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/5HcVoGak8k5agFJSaKa4floXVu0.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/rZ5DdENNqIdFTIyQQiP5isO7M.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/P2Bw01CtL0b9wqygO0sSVogWbo.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/05KsVHGDmqXSBXM4yRZ65P8i0s.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/ky8ovPukK4dJ1Pxq74qGhOqCYI.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/vvNSqIj42qeQ2bvCRBIWKHscrc.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/3ZmXbBKToJifDV9gwcifVd1tEY.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/FNfhX3dt4ChuLJq2PwdlxHO7PU.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/gcnfba68tfm7qAyrWRCf9r34jg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/efTfQcBJ53kM2pB1hezSZ3RDUFs.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
		],
	},
];
var css3 = [
	'.framer-ctc33 .framer-styles-preset-1h22t3d:not(.rich-text-wrapper), .framer-ctc33 .framer-styles-preset-1h22t3d.rich-text-wrapper h3 { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-e1ef367e-e23b-4a9e-826b-77a848c7f0b3, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: capitalize; }',
];
var className3 = "framer-ctc33";

// /:https://framerusercontent.com/modules/XR2vKTkjqToM4G2x4ka1/JOiDggcapErivsjFkaLg/SgMSUVbF9.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Geist-regular",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Geist",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geist/v3/gyBhhwUxId8gMGYQMKR3pzfaWI_RnOM4mJPby1QNtA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css4 = [
	'.framer-SkKbf .framer-styles-preset-k8iid9:not(.rich-text-wrapper), .framer-SkKbf .framer-styles-preset-k8iid9.rich-text-wrapper p { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 10px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-cb2243e7-371d-4dd4-a3f5-00f97c4730ab, #575757); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className4 = "framer-SkKbf";

// /:https://framerusercontent.com/modules/fXb07PP7yomH4X83fOOv/J4gNM5tonKrmA21GiSPN/jR40kgUaq.js
var ImageWithFX = withFX(Image);
var MotionDivWithFX = withFX(motion.div);
var RichTextWithFX = withFX(RichText);
var ButtonFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder = ["iLbYV169T", "Q7YbPOHhV"];
var serializationHash = "framer-JrjFf";
var variantClassNames = {
	iLbYV169T: "framer-v-16e7u5y",
	Q7YbPOHhV: "framer-v-1fzof81",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 60,
	delay: 0.2,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var transition3 = {
	damping: 60,
	delay: 0.4,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition4 = {
	delay: 0,
	duration: 3.5,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 16,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var transition5 = {
	delay: 0,
	duration: 2.5,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: -15,
};
var transition6 = {
	damping: 60,
	delay: 0.5,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var animation4 = {
	opacity: 1,
	rotate: -15,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition7 = {
	damping: 60,
	delay: 0.1,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var animation5 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 80,
};
var transition8 = {
	damping: 60,
	delay: 0.3,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "iLbYV169T",
	"Variant 2": "Q7YbPOHhV",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "iLbYV169T",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "iLbYV169T",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className3, className, className4];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-16e7u5y",
							className5,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"iLbYV169T"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Q7YbPOHhV: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1684r28"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"FJ9IKoN5X"}
						>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-sny4fy"}
								data-framer-name={"Newsletter"}
								layoutDependency={layoutDependency}
								layoutId={"c0fC6XJLq"}
								style={{
									backgroundColor:
										"var(--token-17335ab3-e89a-4abd-b59b-d74d2f34afb2, rgb(255, 255, 255))",
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
									boxShadow: "0px 1px 20px 0px rgba(0, 0, 0, 0.03)",
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 374.75729196300205,
										intrinsicWidth: 541.7475878636144,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												100 +
												(((componentViewport?.height || 570) - 200 - 370) / 2 +
													0 +
													0) +
												0 +
												0 +
												370 -
												283,
										),
										pixelHeight: 386,
										pixelWidth: 558,
										sizes: "442px",
										src: "https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?width=558&height=386",
										srcSet:
											"https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?scale-down-to=512&width=558&height=386 512w,https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?width=558&height=386 558w",
									}}
									className={"framer-5g8ftg"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"z3WXUgeSH"}
									{...addPropertyOverrides(
										{
											Q7YbPOHhV: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 374.75729196300205,
													intrinsicWidth: 541.7475878636144,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															100 +
															(((componentViewport?.height || 570) -
																200 -
																370) /
																2 +
																0 +
																0) +
															0 +
															0 +
															370 -
															191,
													),
													pixelHeight: 386,
													pixelWidth: 558,
													sizes: "442px",
													src: "https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?width=558&height=386",
													srcSet:
														"https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?scale-down-to=512&width=558&height=386 512w,https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?width=558&height=386 558w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 374.75729196300205,
										intrinsicWidth: 541.7475878636144,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												100 +
												(((componentViewport?.height || 570) - 200 - 370) / 2 +
													0 +
													0) +
												0 +
												0 +
												-23.251,
										),
										pixelHeight: 386,
										pixelWidth: 558,
										sizes: "442px",
										src: "https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?width=558&height=386",
										srcSet:
											"https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?scale-down-to=512&width=558&height=386 512w,https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?width=558&height=386 558w",
									}}
									className={"framer-18pnz53"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"NmkBqmz7q"}
									style={{
										rotate: 180,
									}}
									{...addPropertyOverrides(
										{
											Q7YbPOHhV: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 374.75729196300205,
													intrinsicWidth: 541.7475878636144,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															100 +
															(((componentViewport?.height || 570) -
																200 -
																370) /
																2 +
																0 +
																0) +
															0 +
															0 +
															-110.75,
													),
													pixelHeight: 386,
													pixelWidth: 558,
													sizes: "442px",
													src: "https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?width=558&height=386",
													srcSet:
														"https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?scale-down-to=512&width=558&height=386 512w,https://framerusercontent.com/images/OmGZB6Q2bVw2OL3RXRH55t39LWg.png?width=558&height=386 558w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition3,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation1}
									__framer__loop={animation2}
									__framer__loopEffectEnabled={true}
									__framer__loopPauseOffscreen={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"mirror"}
									__framer__loopTransition={transition4}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-c4kmpe"}
									data-framer-name={"Image container"}
									layoutDependency={layoutDependency}
									layoutId={"a0bB60RHy"}
									style={{
										rotate: -19,
									}}
									transformTemplate={transformTemplate1}
								>
									<ImageWithFX
										__framer__loop={animation3}
										__framer__loopEffectEnabled={true}
										__framer__loopPauseOffscreen={true}
										__framer__loopRepeatDelay={0}
										__framer__loopRepeatType={"mirror"}
										__framer__loopTransition={transition5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										background={{
											alt: "Stylized white envelope icon tilted at an angle, representing a message or notification.",
											fit: "fill",
											intrinsicHeight: 460.19418754005954,
											intrinsicWidth: 673.7864264827032,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 570) - 200 - 370) /
														2 +
														0 +
														0) +
													0 +
													0 +
													128.5 +
													0 +
													0,
											),
											pixelHeight: 2861,
											pixelWidth: 4167,
											sizes: "148px",
											src: "https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=1024&width=4167&height=2861",
											srcSet:
												"https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=512&width=4167&height=2861 512w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=1024&width=4167&height=2861 1024w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=2048&width=4167&height=2861 2048w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=4096&width=4167&height=2861 4096w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?width=4167&height=2861 4167w",
										}}
										className={"framer-1vs0qkh"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"I2uazrHlH"}
										style={{
											borderBottomLeftRadius: 10,
											borderBottomRightRadius: 10,
											borderTopLeftRadius: 10,
											borderTopRightRadius: 10,
											boxShadow:
												"0px 0.421531111242075px 1.4332057782230547px -0.9166666666666666px rgba(18, 109, 251, 0.07), 0px 1.60197331227042px 5.446709261719427px -1.8333333333333333px rgba(18, 109, 251, 0.07), 0px 7px 23.799999999999997px -2.75px rgba(18, 109, 251, 0.06), 0px -0.24145061431045178px 0.820932088655536px -1.25px rgba(18, 109, 251, 0.05), 0px -2px 6.8px -2.5px rgba(18, 109, 251, 0.05), 0.421531111242075px 0px 1.4332057782230547px -0.8333333333333333px rgba(18, 109, 251, 0.06), 1.60197331227042px 0px 5.446709261719427px -1.6666666666666665px rgba(18, 109, 251, 0.06), 7px 0px 23.799999999999997px -2.5px rgba(18, 109, 251, 0.06), -0.421531111242075px 0px 1.4332057782230547px -1.4166666666666665px rgba(18, 109, 251, 0.08), -1.60197331227042px 0px 5.446709261719427px -2.833333333333333px rgba(18, 109, 251, 0.07), -7px 0px 23.799999999999997px -4.25px rgba(18, 109, 251, 0.02)",
										}}
										{...addPropertyOverrides(
											{
												Q7YbPOHhV: {
													background: {
														alt: "Stylized white envelope icon tilted at an angle, representing a message or notification.",
														fit: "fill",
														intrinsicHeight: 460.19418754005954,
														intrinsicWidth: 673.7864264827032,
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 570) -
																	200 -
																	370) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																179 +
																0 -
																-73,
														),
														pixelHeight: 2861,
														pixelWidth: 4167,
														sizes: "75px",
														src: "https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=1024&width=4167&height=2861",
														srcSet:
															"https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=512&width=4167&height=2861 512w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=1024&width=4167&height=2861 1024w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=2048&width=4167&height=2861 2048w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=4096&width=4167&height=2861 4096w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?width=4167&height=2861 4167w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</MotionDivWithFX>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition6,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation1}
									__framer__loop={animation4}
									__framer__loopEffectEnabled={true}
									__framer__loopPauseOffscreen={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"mirror"}
									__framer__loopTransition={transition4}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-gdggxc"}
									data-framer-name={"Image container"}
									layoutDependency={layoutDependency}
									layoutId={"BK5IzyO13"}
									style={{
										rotate: 9,
									}}
								>
									<ImageWithFX
										__framer__loop={animation3}
										__framer__loopEffectEnabled={true}
										__framer__loopPauseOffscreen={true}
										__framer__loopRepeatDelay={0}
										__framer__loopRepeatType={"mirror"}
										__framer__loopTransition={transition5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										background={{
											alt: "Stylized white envelope icon tilted at an angle, representing a message or notification.",
											fit: "fill",
											intrinsicHeight: 460.19418754005954,
											intrinsicWidth: 673.7864264827032,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 570) - 200 - 370) /
														2 +
														0 +
														0) +
													0 +
													0 +
													144.0006 +
													0 +
													0,
											),
											pixelHeight: 2861,
											pixelWidth: 4167,
											sizes: "148px",
											src: "https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=1024&width=4167&height=2861",
											srcSet:
												"https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=512&width=4167&height=2861 512w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=1024&width=4167&height=2861 1024w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=2048&width=4167&height=2861 2048w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=4096&width=4167&height=2861 4096w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?width=4167&height=2861 4167w",
										}}
										className={"framer-qac5e9"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"o3PlOWHnn"}
										style={{
											borderBottomLeftRadius: 10,
											borderBottomRightRadius: 10,
											borderTopLeftRadius: 10,
											borderTopRightRadius: 10,
											boxShadow:
												"0px 0.421531111242075px 1.4332057782230547px -0.9166666666666666px rgba(18, 109, 251, 0.07), 0px 1.60197331227042px 5.446709261719427px -1.8333333333333333px rgba(18, 109, 251, 0.07), 0px 7px 23.799999999999997px -2.75px rgba(18, 109, 251, 0.06), 0px -0.24145061431045178px 0.820932088655536px -1.25px rgba(18, 109, 251, 0.05), 0px -2px 6.8px -2.5px rgba(18, 109, 251, 0.05), 0.421531111242075px 0px 1.4332057782230547px -0.8333333333333333px rgba(18, 109, 251, 0.06), 1.60197331227042px 0px 5.446709261719427px -1.6666666666666665px rgba(18, 109, 251, 0.06), 7px 0px 23.799999999999997px -2.5px rgba(18, 109, 251, 0.06), -0.421531111242075px 0px 1.4332057782230547px -1.4166666666666665px rgba(18, 109, 251, 0.08), -1.60197331227042px 0px 5.446709261719427px -2.833333333333333px rgba(18, 109, 251, 0.07), -7px 0px 23.799999999999997px -4.25px rgba(18, 109, 251, 0.02)",
										}}
										{...addPropertyOverrides(
											{
												Q7YbPOHhV: {
													background: {
														alt: "Stylized white envelope icon tilted at an angle, representing a message or notification.",
														fit: "fill",
														intrinsicHeight: 460.19418754005954,
														intrinsicWidth: 673.7864264827032,
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 570) -
																	200 -
																	370) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																144.0006 +
																-113,
														),
														pixelHeight: 2861,
														pixelWidth: 4167,
														src: "https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=1024&width=4167&height=2861",
														srcSet:
															"https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=512&width=4167&height=2861 512w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=1024&width=4167&height=2861 1024w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=2048&width=4167&height=2861 2048w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?scale-down-to=4096&width=4167&height=2861 4096w,https://framerusercontent.com/images/OXyYHX9MW2fCN7IDYfVvNCAqUX0.png?width=4167&height=2861 4167w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</MotionDivWithFX>
								<motion.div
									className={"framer-uwmqla"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"I5H8ND2Dh"}
								>
									<motion.div
										className={"framer-11gbxb"}
										data-framer-name={"Heading + Text"}
										layoutDependency={layoutDependency}
										layoutId={"ZDSg4Iu8s"}
									>
										<RichTextWithFX
											__framer__animate={{
												transition: transition7,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-30a1px"}
											data-framer-name={"Heading"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"sgB05DAel"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													Q7YbPOHhV: {
														children: (
															<React.Fragment>
																<motion.h3
																	className={"framer-styles-preset-1h22t3d"}
																	data-styles-preset={"aEzDQzBLB"}
																	style={{
																		"--framer-text-alignment": "center",
																	}}
																>
																	{"Subscribe to the AI2Market Newsletter!"}
																</motion.h3>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h2
													className={"framer-styles-preset-xrkfmc"}
													data-styles-preset={"v3uTk3d0Q"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"Subscribe to the AI2Market Newsletter!"}
												</motion.h2>
											</React.Fragment>
										</RichTextWithFX>
										<RichTextWithFX
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation5}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0.5}
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-120yo3p"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"v1OL846hu"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													Q7YbPOHhV: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-k8iid9"}
																	data-styles-preset={"SgMSUVbF9"}
																	style={{
																		"--framer-text-alignment": "center",
																	}}
																>
																	{
																		"Get expert tips, updates, and smart analytics insights delivered straight to your inbox."
																	}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-oo9bt8"}
													data-styles-preset={"Qd8jNwk_8"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{
														"Get expert tips, updates, and smart analytics insights delivered straight to your inbox."
													}
												</motion.p>
											</React.Fragment>
										</RichTextWithFX>
									</motion.div>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "oZLBf0uQT",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "oZLBf0uQT",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={42}
												y={
													(componentViewport?.y || 0) +
													100 +
													(((componentViewport?.height || 570) - 200 - 370) /
														2 +
														0 +
														0) +
													0 +
													0 +
													40 +
													38.55 +
													0 +
													170.9
												}
												{...addPropertyOverrides(
													{
														Q7YbPOHhV: {
															y:
																(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 570) -
																	200 -
																	370) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																40 +
																-35 +
																98 +
																122,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainerWithFX
													__framer__animate={{
														transition: transition8,
													}}
													__framer__animateOnce={true}
													__framer__enter={animation}
													__framer__styleAppearEffectEnabled={true}
													__framer__threshold={0.5}
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													className={"framer-10dhtin-container"}
													layoutDependency={layoutDependency}
													layoutId={"tGULKBiXY-container"}
													nodeId={"tGULKBiXY"}
													rendersWithMotion={true}
													scopeId={"jR40kgUaq"}
												>
													{_jsx(stdin_default, {
														e5w0UxZNt: resolvedLinks[0],
														height: "100%",
														hKzSQEl_0: "Subscribe Now",
														id: "tGULKBiXY",
														layoutId: "tGULKBiXY",
														VEpndFiaz: false,
														width: "100%",
														...addPropertyOverrides(
															{
																Q7YbPOHhV: {
																	e5w0UxZNt: resolvedLinks[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainerWithFX>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion.div>
							</MotionDivWithFX>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JrjFf.framer-1r8j00g, .framer-JrjFf .framer-1r8j00g { display: block; }",
	".framer-JrjFf.framer-16e7u5y { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 0px 100px 0px; position: relative; width: 1200px; }",
	".framer-JrjFf .framer-1684r28 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; max-width: 1200px; overflow: visible; padding: 0px 48px 0px 48px; position: relative; width: 100%; }",
	".framer-JrjFf .framer-sny4fy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 370px; justify-content: center; overflow: hidden; padding: 40px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-JrjFf .framer-5g8ftg { aspect-ratio: 1.4455958549222798 / 1; bottom: -23px; flex: none; height: var(--framer-aspect-ratio-supported, 306px); overflow: visible; position: absolute; right: -140px; width: 442px; z-index: 0; }",
	".framer-JrjFf .framer-18pnz53 { aspect-ratio: 1.4455958549222798 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 306px); left: -140px; overflow: visible; position: absolute; top: -23px; width: 442px; z-index: 0; }",
	".framer-JrjFf .framer-c4kmpe { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 70px; overflow: visible; padding: 0px; position: absolute; top: 48%; width: min-content; z-index: 1; }",
	".framer-JrjFf .framer-1vs0qkh, .framer-JrjFf .framer-qac5e9 { aspect-ratio: 1.4641350210970463 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 101px); overflow: visible; position: relative; width: 148px; }",
	".framer-JrjFf .framer-gdggxc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: absolute; right: 60px; top: 144px; width: min-content; z-index: 1; }",
	".framer-JrjFf .framer-uwmqla { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-JrjFf .framer-11gbxb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-JrjFf .framer-30a1px { flex: none; height: auto; max-width: 450px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-JrjFf .framer-120yo3p { flex: none; height: auto; max-width: 320px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-JrjFf .framer-10dhtin-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-JrjFf.framer-v-1fzof81.framer-16e7u5y { width: 390px; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-5g8ftg { bottom: -115px; right: -195px; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-18pnz53 { left: -229px; top: -111px; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-c4kmpe { min-height: 35px; min-width: 51px; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-1vs0qkh { bottom: -124px; height: var(--framer-aspect-ratio-supported, 51px); left: -87px; order: 0; position: absolute; width: 75px; z-index: 1; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-gdggxc { min-height: 36px; min-width: 52px; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-qac5e9 { height: var(--framer-aspect-ratio-supported, 48px); left: -10px; order: 0; position: absolute; right: -8px; top: -113px; width: unset; z-index: 1; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-uwmqla { padding: 98px 0px 98px 0px; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-11gbxb, .framer-JrjFf.framer-v-1fzof81 .framer-30a1px { order: 0; }",
	".framer-JrjFf.framer-v-1fzof81 .framer-120yo3p, .framer-JrjFf.framer-v-1fzof81 .framer-10dhtin-container { order: 1; }",
	...css2,
	...css3,
	...css,
	...css4,
];
var FramerjR40kgUaq = withCSS(Component, css5, "framer-JrjFf");
var stdin_default2 = FramerjR40kgUaq;
FramerjR40kgUaq.displayName = "Newsletter";
FramerjR40kgUaq.defaultProps = {
	height: 570,
	width: 1200,
};
addPropertyControls(FramerjR40kgUaq, {
	variant: {
		options: ["iLbYV169T", "Q7YbPOHhV"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerjR40kgUaq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:newsletter
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Q7YbPOHhV",
	xl: "iLbYV169T",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NewsletterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"ac4b2f1e7a67ec54d9e1f0f895388d854ea5f62d2263dbdc35029091e7184968"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var newsletter_default = ComponentWithRoot;
export { newsletter_default as default };
